pyVerein/app/urls.py
# Import django-urls.
from django.urls import path
# Import views.
from . import views

# Set app name
app_name = 'app'
# Set url-patterns
urlpatterns = [
    path('', views.index, name='index'),
]

pyVerein/finance/urls.py
# Import django-urls.
from django.urls import path
# Import views.
from . import views

# Set app name
app_name = 'finance'
# Set url-patterns
urlpatterns = [
    path('creditor/', views.CreditorIndexView.as_view(), name='creditor_list'),
    path('creditor/new/', views.CreditorCreateView.as_view(), name='creditor_create'),
    path('creditor/<str:pk>/', views.CreditorDetailView.as_view(), name='creditor_detail'),
    path('creditor/<str:pk>/edit/', views.CreditorEditView.as_view(), name='creditor_edit'),
    path('creditor/<str:account>/clearing/', views.CreditorClearingView.as_view(), name='creditor_clear'),

    path('debitor/', views.DebitorIndexView.as_view(), name='debitor_list'),
    path('debitor/new/', views.DebitorCreateView.as_view(), name='debitor_create'),
    path('debitor/<str:pk>/', views.DebitorDetailView.as_view(), name='debitor_detail'),
    path('debitor/<str:pk>/edit/', views.DebitorEditView.as_view(), name='debitor_edit'),
    path('debitor/<str:account>/clearing/', views.DebitorClearingView.as_view(), name='debitor_clear'),

    path('impersonal/', views.ImpersonalIndexView.as_view(), name='impersonal_list'),
    path('impersonal/new/', views.ImpersonalCreateView.as_view(), name='impersonal_create'),
    path('impersonal/<str:pk>/', views.ImpersonalDetailView.as_view(), name='impersonal_detail'),
    path('impersonal/<str:pk>/edit/', views.ImpersonalEditView.as_view(), name='impersonal_edit'),

    path('costcenter/', views.CostCenterIndexView.as_view(), name='costcenter_list'),
    path('costcenter/new/', views.CostCenterCreateView.as_view(), name='costcenter_create'),
    path('costcenter/<str:pk>/', views.CostCenterDetailView.as_view(), name='costcenter_detail'),
    path('costcenter/<str:pk>/edit/', views.CostCenterEditView.as_view(), name='costcenter_edit'),

    path('costobject/', views.CostObjectIndexView.as_view(), name='costobject_list'),
    path('costobject/new/', views.CostObjectCreateView.as_view(), name='costobject_create'),
    path('costobject/<str:pk>/', views.CostObjectDetailView.as_view(), name='costobject_detail'),
    path('costobject/<str:pk>/edit/', views.CostObjectEditView.as_view(), name='costobject_edit'),

    path('transaction/', views.TransactionIndexView.as_view(), name='transaction_list'),
    path('transaction/new/', views.TransactionCreateView.as_view(), name='transaction_create'),
    path('transaction/new/<str:session_id>/', views.TransactionCreateView.as_view(), name='transaction_create_session'),
    path('transaction/new/<str:session_id>/<int:step>/', views.TransactionCreateView.as_view(), name='transaction_create_step'),
    path('transaction/<int:internal_number>/', views.TransactionDetailView.as_view(), name='transaction_detail'),
    path('transaction/<int:internal_number>/edit/<int:pk>/', views.TransactionEditView.as_view(), name='transaction_edit'),
    path('transaction/<int:internal_number>/reset', views.reset_transaction, name='transaction_reset'),
    path('transaction/<int:internal_number>/reset_new', views.reset_new_transaction, name='transaction_reset_new'),

    path('virtual_account/', views.VirtualAccountIndexView.as_view(), name='virtual_account_list'),
    path('virtual_account/new/', views.VirtualAccountCreateView.as_view(), name='virtual_account_create'),
    path('virtual_account/<str:pk>/', views.VirtualAccountDetailView.as_view(), name='virtual_account_detail'),
    path('virtual_account/<str:pk>/edit/', views.VirtualAccountEditView.as_view(), name='virtual_account_edit'),

    path('api/account/<str:search>', views.get_account, name='account_search'),
    path('api/costcenter/<str:search>', views.get_cost_center, name='costcenter_search'),
    path('api/costobject/<str:search>', views.get_cost_object, name='costobject_search'),
    path('api/clearing/', views.clear_transaction, name='clear_transactions'),
    path('api/clearing/reset/', views.reset_cleared_transaction, name='reset_cleared_transactions'),
] 

pyVerein/members/urls.py
# Import django-urls.
from django.urls import path
# Import views.
from . import views

# Set app name
app_name = 'members'
# Set url-patterns
urlpatterns = [
    path('member/', views.MemberIndexView.as_view(), name='member_list'),
    path('member/new/', views.MemberCreateView.as_view(), name='member_create'),
    path('member/<int:pk>/', views.MemberDetailView.as_view(), name='member_detail'),
    path('member/edit/<int:pk>/', views.MemberEditView.as_view(), name='member_edit'),
    path('upload_file/<int:pk>/', views.upload_file, name='member_upload_file'),
    path('delete_file/<int:pk>/', views.delete_file, name='member_delete_file'),
    path('download_file/<int:pk>/', views.download_file, name='member_download_file'),

    path('division/', views.DivisionIndexView.as_view(), name='division_list'),
    path('division/new/', views.DivisionCreateView.as_view(), name='division_create'),
    path('division/<int:pk>/', views.DivisionDetailView.as_view(), name='division_detail'),
    path('division/edit/<int:pk>/', views.DivisionEditView.as_view(), name='division_edit'),

    path('subscription/', views.SubscriptionIndexView.as_view(), name='subscription_list'),
    path('subscription/new/', views.SubscriptionCreateView.as_view(), name='subscription_create'),
    path('subscription/<int:pk>/', views.SubscriptionDetailView.as_view(), name='subscription_detail'),
    path('subscription/edit/<int:pk>/', views.SubscriptionEditView.as_view(), name='subscription_edit'),
]

pyVerein/reporting/urls.py
# Import django-urls.
from django.urls import path
# Import views.
from . import views

# Set app name
app_name = 'reporting'
# Set url-patterns
urlpatterns = [
    path('', views.ReportIndexView.as_view(), name='list'),
    path('new/', views.ReportCreateView.as_view(), name='create'),
    path('<int:pk>/', views.ReportDetailView.as_view(), name='detail'),
    path('edit/<int:pk>/', views.ReportEditView.as_view(), name='edit'),
    path('run/<int:pk>/', views.run_report, name='run'),
    path('download_report/<int:pk>/', views.download_report, name='download_report'),
    path('upload_resource/<int:pk>/', views.upload_resource, name='upload_resource'),
    path('delete_resource/<int:pk>/', views.delete_resource, name='delete_resource'),
    path('download_resource/<int:pk>/', views.download_resource, name='download_resource'),
    path('download_data/', views.download_data, name='download_data'),
] 

pyVerein/tasks/urls.py
# Import django-urls.
from django.urls import path
# Import views.
from . import views

# Set app name
app_name = 'tasks'
# Set url-patterns
urlpatterns = [
    path('', views.TaskIndexView.as_view(), name='task_list'),
    path('apply_subscriptions/', views.apply_subscriptions, name='apply_subscriptions'),
    path('apply_annualclosure/', views.apply_annualclosure, name='apply_annualclosure'),
    path('delete_terminated_members/', views.delete_terminated_members, name='delete_terminated_members'),
    path('delete_report_data/', views.delete_report_data, name='delete_report_data'),
] 

pyVerein/app/templates/app/_attributions.html
{% load i18n %}
<div class="mdc-dialog" id="attribution-dialog">
    <div class="mdc-dialog__scrim"></div>
    <div class="mdc-dialog__container">
        <div class="mdc-dialog__surface">
            <h2 class="mdc-dialog__title">{% trans 'Attributions' %}</h2>
            <section class="mdc-dialog__content">
                <p>
                    <h4>
                        Abel font
                    </h4>
                    <span class="mdc-typography--overline">Abel</span> {% trans 'by' %} Matthew Desmond<br />
                    {% trans 'Published under' %} <a href="https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL_web" title="Open Font License" target="_blank">Open Font License</a> {% trans 'at' %} <a href="https://fonts.google.com/specimen/Abel" title="{% trans 'Open at' %} fonts.google.com" target="_blank">fonts.google.com</a>
                </p>
                <p>
                    <h4>
                        animate.css
                    </h4>
                    <span class="mdc-typography--overline">animate.css</span> {% trans 'by' %} Daniel Eden<br />
                    {% trans 'Published under' %} <a href="http://opensource.org/licenses/MIT" title="MIT" target="_blank">MIT-License</a> {% trans 'at' %} <a href="https://daneden.github.io/animate.css/" title="{% trans 'Open at' %} github.io" target="_blank">daneden.github.io</a>
                </p>
                <p>
                    <h4>
                        Bootstrap Notify
                    </h4>
                    <span class="mdc-typography--overline">Bootstrap Notify</span> {% trans 'by' %} Robert McIntosh<br />
                    {% trans 'Published under' %} <a href="http://opensource.org/licenses/MIT" title="MIT" target="_blank">MIT-License</a> {% trans 'at' %} <a href="http://bootstrap-notify.remabledesigns.com/" title="{% trans 'Open at' %} remabledesigns.com" target="_blank">remabledesigns.com</a>
                </p>
                <p>
                    <h4>
                        c3.js
                    </h4>
                    <span class="mdc-typography--overline">c3.js</span> {% trans 'by' %} Masayuki Tanaka<br />
                    {% trans 'Published under' %} <a href="http://opensource.org/licenses/MIT" title="MIT" target="_blank">MIT-License</a> {% trans 'at' %} <a href="https://c3js.org/" title="{% trans 'Open at' %} c3js.org" target="_blank">c3js.org</a>
                </p>
                <p>
                    <h4>
                        DataTables.net
                    </h4>
                    <span class="mdc-typography--overline">DataTables.net</span> {% trans 'by' %} SpryMedia Ltd.<br />
                    {% trans 'Published under' %} <a href="http://opensource.org/licenses/MIT" title="MIT" target="_blank">MIT-License</a> {% trans 'at' %} <a href="https://datatables.net/" title="{% trans 'Open at' %} datatables.net" target="_blank">datatables.net</a>
                </p>
                <p>
                    <h4>
                        decimal.js
                    </h4>
                    <span class="mdc-typography--overline">decimal.js</span> {% trans 'by' %} MikeMcl<br />
                    {% trans 'Published under' %} <a href="http://opensource.org/licenses/MIT" title="MIT" target="_blank">MIT-License</a> {% trans 'at' %} <a href="http://mikemcl.github.io/decimal.js/" title="{% trans 'Open at' %} github.io" target="_blank">mikemcl.github.io</a>
                </p>
                <p>
                    <h4>
                        Django-Author
                    </h4>
                    <span class="mdc-typography--overline">Django-Author</span> {% trans 'by' %} lambdalisue<br />
                    {% trans 'Published under' %} <a href="http://www.apache.org/licenses/LICENSE-2.0.txt" title="Apache License Version 2.0" target="_blank">Apache License Version 2.0</a> {% trans 'at' %} <a href="https://github.com/lambdalisue/django-author" title="{% trans 'Open at' %} github.com" target="_blank">github.com</a>
                </p>
                <p>
                    <h4>
                        Django-Dynamic-Preferences
                    </h4>
                    <span class="mdc-typography--overline">Django-Dynamic-Preferences</span> {% trans 'by' %} Eliot Berriot<br />
                    {% trans 'Published under' %} <a href="https://opensource.org/licenses/BSD-3-Clause" title="BSD-3-Clause" target="_blank">BSD-3-Clause</a> {% trans 'at' %} <a href="https://github.com/EliotBerriot/django-dynamic-preferences/" title="{% trans 'Open at' %} github.com" target="_blank">github.com</a>
                </p>
                <p>
                    <h4>
                        Django Sendfile 2
                    </h4>
                    <span class="mdc-typography--overline">Django Sendfile 2</span> {% trans 'by' %} Matt Molyneaux<br />
                    {% trans 'Published under' %} <a href="https://github.com/moggers87/django-sendfile2/blob/master/LICENSE" title="BSD-License" target="_blank">BSD-License</a> {% trans 'at' %} <a href="https://github.com/moggers87/django-sendfile2" title="{% trans 'Open at' %} github.com" target="_blank">github.com</a>
                </p>
                <p>
                    <h4>
                        Django-Seperatedvaluesfield
                    </h4>
                    <span class="mdc-typography--overline">Django-Seperatedvaluesfield</span> {% trans 'by' %} ulule<br />
                    {% trans 'Published under' %} <a href="http://opensource.org/licenses/MIT" title="MIT" target="_blank">MIT-License</a> {% trans 'at' %} <a href="https://github.com/ulule/django-separatedvaluesfield" title="{% trans 'Open at' %} github.com" target="_blank">github.com</a>
                </p>
                <p>
                    <h4>
                        Django-Simple-History
                    </h4>
                    <span class="mdc-typography--overline">Django-Simple-History</span> {% trans 'by' %} Trey Hunner<br />
                    {% trans 'Published under' %} <a href="https://github.com/treyhunner/django-simple-history/blob/master/LICENSE.txt" title="BSD-License" target="_blank">BSD3-License</a> {% trans 'at' %} <a href="https://github.com/treyhunner/django-simple-history" title="{% trans 'Open at' %} github.com" target="_blank">github.com</a>
                </p>
                <p>
                    <h4>
                        Django Two-Factor Authentication
                    </h4>
                    <span class="mdc-typography--overline">Django Two-Factor Authentication</span> {% trans 'by' %} Bouke<br />
                    {% trans 'Published under' %} <a href="http://opensource.org/licenses/MIT" title="MIT" target="_blank">MIT-License</a> {% trans 'at' %} <a href="https://github.com/Bouke/django-two-factor-auth" title="{% trans 'Open at' %} github.com" target="_blank">github.com</a>
                </p>
                <p>
                    <h4>
                        Django-Widget-Tweaks
                    </h4>
                    <span class="mdc-typography--overline">Django-Widget-Tweaks</span> {% trans 'by' %} jazzband.co<br />
                    {% trans 'Published under' %} <a href="http://opensource.org/licenses/MIT" title="MIT" target="_blank">MIT-License</a> {% trans 'at' %} <a href="https://github.com/jazzband/django-widget-tweaks/" title="{% trans 'Open at' %} github.com" target="_blank">github.com</a>
                </p>
                <p>
                    <h4>
                        Font Awesome
                    </h4>
                    <span class="mdc-typography--overline">Font Awesome</span> {% trans 'by' %} Fonticons, Inc.<br />
                    {% trans 'Published under' %} <a href="https://fontawesome.com/license/free" title="Font Awesome Free License" target="_blank">Font Awesome Free License</a> {% trans 'at' %} <a href="https://fontawesome.com/" title="{% trans 'Open at' %} fontawesome.com" target="_blank">fontawesome.com</a>
                </p>
                <p>
                    <h4>
                        jQuery
                    </h4>
                    <span class="mdc-typography--overline">jQuery</span> {% trans 'by' %} The jQuery Foundation<br />
                    {% trans 'Published under' %} <a href="https://jquery.org/license/" title="jQuery License" target="_blank">jQuery License</a> {% trans 'at' %} <a href="https://jquery.org/" title="{% trans 'Open at' %} jquery.org" target="_blank">jquery.org</a>
                </p>
                <p>
                    <h4>
                        jquery.inputmask
                    </h4>
                    <span class="mdc-typography--overline">jquery.inputmask</span> {% trans 'by' %} Robin Herbots<br />
                    {% trans 'Published under' %} <a href="http://opensource.org/licenses/MIT" title="MIT" target="_blank">MIT-License</a> {% trans 'at' %} <a href="https://robinherbots.github.io/Inputmask/" title="{% trans 'Open at' %} github.io" target="_blank">github.io</a>
                </p>
                <p>
                    <h4>
                        Material components
                    </h4>
                    <span class="mdc-typography--overline">Material components</span> {% trans 'by' %} Google<br />
                    {% trans 'Published under' %} <a href="http://opensource.org/licenses/MIT" title="MIT" target="_blank">MIT-License</a> {% trans 'at' %} <a href="https://material.io/develop/web/" title="{% trans 'Open at' %} material.io" target="_blank">material.io</a>
                </p>
                <p>
                    <h4>
                        Material icons
                    </h4>
                    <span class="mdc-typography--overline">Material icons</span> {% trans 'by' %} Google<br />
                    {% trans 'Published under' %} <a href="http://www.apache.org/licenses/LICENSE-2.0.txt" title="Apache License Version 2.0" target="_blank">Apache License Version 2.0</a> {% trans 'at' %} <a href="https://material.io/tools/icons/" title="{% trans 'Open at' %} material.io" target="_blank">material.io</a>
                </p>
                <p>
                    <h4>
                        OverlayScrollbars
                    </h4>
                    <span class="mdc-typography--overline">OverlayScrollbars</span> {% trans 'by' %} Rene Haas<br />
                    {% trans 'Published under' %} <a href="http://opensource.org/licenses/MIT" title="MIT" target="_blank">MIT-License</a> {% trans 'at' %} <a href="https://github.com/KingSora/OverlayScrollbars" title="{% trans 'Open at' %} github.com" target="_blank">github.com</a>
                </p>
                <p>
                    <h4>
                        PyReportJasper
                    </h4>
                    <span class="mdc-typography--overline">PyReportJasper</span> {% trans 'by' %} jadsonbr<br />
                    {% trans 'Published under' %} <a href="http://opensource.org/licenses/MIT" title="MIT" target="_blank">MIT-License</a> {% trans 'at' %} <a href="https://github.com/PyReportJasper/pyreportjasper" title="{% trans 'Open at' %} github.com" target="_blank">github.com</a>
                </p>
                <p>
                    <h4>
                        SpinKit
                    </h4>
                    <span class="mdc-typography--overline">SpinKit</span> {% trans 'by' %} Tobias Ahlin<br />
                    {% trans 'Published under' %} <a href="http://opensource.org/licenses/MIT" title="MIT" target="_blank">MIT-License</a> {% trans 'at' %} <a href="http://tobiasahlin.com/spinkit/" title="{% trans 'Open at' %} tobiasahlin.com" target="_blank">tobiasahlin.com</a>
                </p>
                <p>
                    <h4>
                        Standard Avatar-Image
                    </h4>
                    <span class="mdc-typography--overline">Free avatars flat icons</span> {% trans 'by' %} Dmitriy Bondarchuk<br />
                    {% trans 'Published under' %} <a href="https://creativecommons.org/licenses/by-nc-nd/4.0/" title="CC BY-NC-ND 4.0" target="_blank">CC BY-NC-ND 4.0</a> {% trans 'at' %} <a href="https://www.behance.net/gallery/47035405/Free-avatars-flat-icons" title="{% trans 'Open at' %} behance.net" target="_blank">behance.net</a>
                </p>
            </section>
            <footer class="mdc-dialog__actions">
                <button type="button" class="mdc-button mdc-dialog__button" title="{% trans 'Close' %}" data-mdc-dialog-action="close">{% trans 'Close' %}</button>
            </footer>
        </div>
    </div>
</div>

pyVerein/app/templates/app/_drawer.html
{% load static %} {% load i18n %} {% load menu %}
<aside class="mdc-drawer mdc-drawer--modal mdc-typography main-navigation">
    <div class="mdc-drawer__header mdc-theme--primary-bg">
        <div class="mdc-drawer__title">
            <div class="logo">
                <a href="{% url 'app:index' %}" class="site_title" title="{% trans 'Dashboard' %}">
                    <img src="{% static 'app/images/logo_white.png' %}" />
                </a>
            </div>           
        </div>
    </div>
    <div class="mdc-drawer__content">
        <nav class="mdc-list">
            {% if perms.members.view_member or perms.members.view_division or perms.members.view_subscription %}
            <h3 class="mdc-list-group__subheader">{% trans 'Members' %}</h3>
            {% endif %}
            {% if perms.members.view_member%}
            <a href="{% url 'members:member_list' %}" title="{% trans 'Members' %}" class="mdc-list-item {% base_url_class 'members:member_list' 'mdc-list-item--activated'%}" target="_blank">
                <span class="mdc-list-item__graphic fa fa-users" aria-hidden="true"></span>
                <span class="mdc-list-item__text">{% trans 'Members' %}</span>
            </a>
            {% endif %}
            {% if perms.members.view_division %}
            <a href="{% url 'members:division_list' %}" title="{% trans 'Divisions' %}" class="mdc-list-item {% base_url_class 'members:division_list' 'mdc-list-item--activated'%}" target="_blank">
                <span class="mdc-list-item__graphic fa fa-sitemap" aria-hidden="true"></span>
                <span class="mdc-list-item__text">{% trans 'Divisions' %}</span>
            </a>
            {% endif %}
            {% if perms.members.view_subscription %}
            <a href="{% url 'members:subscription_list' %}" title="{% trans 'Subscriptions' %}" class="mdc-list-item {% base_url_class 'members:subscription_list' 'mdc-list-item--activated'%}" target="_blank">
                <span class="mdc-list-item__graphic fa fa-money-bill-alt" aria-hidden="true"></span>
                <span class="mdc-list-item__text">{% trans 'Subscriptions' %}</span>
            </a>
            {% endif %}
            {% if perms.members.view_member or perms.members.view_division or perms.members.view_subscription %}
            <hr class="mdc-list-divider">
            {% endif %}
            {% if perms.finance.view_transaction or perms.finance.view_debitor or perms.finance.view_creditor or perms.finance.view_impersonal or perms.finance.view_costcenter or perms.finance.view_costobject %}
            <h3 class="mdc-list-group__subheader">{% trans 'Finance' %}</h3>
            {% endif %}
            {% if perms.finance.view_transaction %}
            <a href="{% url 'finance:transaction_list' %}" title="{% trans 'Transactions' %}" class="mdc-list-item {% base_url_class 'finance:transaction_list' 'mdc-list-item--activated'%}" target="_blank">
                <span class="mdc-list-item__graphic fa fa-file-alt" aria-hidden="true"></span>
                <span class="mdc-list-item__text">{% trans 'Transactions' %}</span>
            </a>
            {% endif %}
            {% if perms.finance.view_debitor %}
            <a href="{% url 'finance:debitor_list' %}" title="{% trans 'Debitors' %}" class="mdc-list-item {% base_url_class 'finance:debitor_list' 'mdc-list-item--activated'%}" target="_blank">
                <span class="mdc-list-item__graphic fa fa-user-plus" aria-hidden="true"></span>
                <span class="mdc-list-item__text">{% trans 'Debitors' %}</span>
            </a>
            {% endif %}
            {% if perms.finance.view_creditor %}
            <a href="{% url 'finance:creditor_list' %}" title="{% trans 'Creditors' %}" class="mdc-list-item {% base_url_class 'finance:creditor_list' 'mdc-list-item--activated'%}" target="_blank">
                <span class="mdc-list-item__graphic fa fa-user-times" aria-hidden="true"></span>
                <span class="mdc-list-item__text">{% trans 'Creditors' %}</span>
            </a>
            {% endif %}
            {% if perms.finance.view_impersonal %}
            <a href="{% url 'finance:impersonal_list' %}" title="{% trans 'Impersonal' %}" class="mdc-list-item {% base_url_class 'finance:impersonal_list' 'mdc-list-item--activated'%}" target="_blank">
                <span class="mdc-list-item__graphic fa fa-box" aria-hidden="true"></span>
                <span class="mdc-list-item__text">{% trans 'Impersonal' %}</span>
            </a>
            {% endif %}
            {% if perms.finance.view_costcenter %}
            <a href="{% url 'finance:costcenter_list' %}" title="{% trans 'Cost centers' %}" class="mdc-list-item {% base_url_class 'finance:costcenter_list' 'mdc-list-item--activated'%}" target="_blank">
                <span class="mdc-list-item__graphic fa fa-money-bill-alt" aria-hidden="true"></span>
                <span class="mdc-list-item__text">{% trans 'Cost centers' %}</span>
            </a>
            {% endif %}
            {% if perms.finance.view_costobject %}
            <a href="{% url 'finance:costobject_list' %}" title="{% trans 'Cost objects' %}" class="mdc-list-item {% base_url_class 'finance:costobject_list' 'mdc-list-item--activated'%}" target="_blank">
                <span class="mdc-list-item__graphic fa fa-money-bill-alt" aria-hidden="true"></span>
                <span class="mdc-list-item__text">{% trans 'Cost objects' %}</span>
            </a>
            {% endif %}
            {% if perms.finance.view_virtualaccount %}
            <a href="{% url 'finance:virtual_account_list' %}" title="{% trans 'Virtual accounts' %}" class="mdc-list-item {% base_url_class 'finance:virtual_account_list' 'mdc-list-item--activated'%}" target="_blank">
                <span class="mdc-list-item__graphic fas fa-funnel-dollar" aria-hidden="true"></span>
                <span class="mdc-list-item__text">{% trans 'Virtual accounts' %}</span>
            </a>
            {% endif %}
            {% if perms.finance.view_transaction or perms.finance.view_debitor or perms.finance.view_creditor or perms.finance.view_costcenter or perms.finance.view_costobject %}
            <hr class="mdc-list-divider">
            {% endif %}
            {% if perms.tasks.view_tasks %}
            <h3 class="mdc-list-group__subheader">{% trans 'Tasks' %}</h3>
            {% endif %}
            {% if perms.tasks.view_tasks %}
            <a href="{% url 'tasks:task_list' %}" title="{% trans 'Tasks' %}" class="mdc-list-item {% base_url_class 'tasks:task_list' 'mdc-list-item--activated'%}" target="_blank">
                <span class="mdc-list-item__graphic fa fa-tasks" aria-hidden="true"></span>
                <span class="mdc-list-item__text">{% trans 'Tasks' %}</span>
            </a>
            {% endif %}
            {% if perms.tasks.view_tasks %}
            <hr class="mdc-list-divider">
            {% endif %}
            {% if perms.reporting.view_report %}
            <h3 class="mdc-list-group__subheader">{% trans 'Reporting' %}</h3>
            {% endif %}
            {% if perms.reporting.view_report %}
            <a href="{% url 'reporting:list' %}" title="{% trans 'Reports' %}" class="mdc-list-item {% base_url_class 'reporting:list' 'mdc-list-item--activated'%}" target="_blank">
                <span class="mdc-list-item__graphic fa fa-chart-pie" aria-hidden="true"></span>
                <span class="mdc-list-item__text">{% trans 'Reports' %}</span>
            </a>
            {% endif %}
            {% if perms.reporting.view_report %}
            <hr class="mdc-list-divider">
            {% endif %}
        </nav>
    </div>
</aside>

pyVerein/app/templates/app/_history.html
{% load i18n %}{% load historytype %}
<div class="mdc-dialog" id="history-dialog">
    <div class="mdc-dialog__scrim"></div>
    <div class="mdc-dialog__container">
        <div class="mdc-dialog__surface">
            <h2 class="mdc-dialog__title">{% trans 'History' %}</h2>
            <section class="mdc-dialog__content">
                <div class="timeline-wrapper">
                    {% for record in history %}
                        <div class="timeline-step">
                            <div class="step-header">
                                <div class="step-icon {% historytype record.type %}"></div>
                                <div class="step-text heading mdc-typography--overline">{{ record.date }} - {{ record.user }}</div>
                            </div>
                            <div class="step-content">
                                <div class="step-connector">
                                </div>
                                <div class="step-inner">
                                    {% if record.type == "+" %}
                                        {% trans 'Record created' %}
                                    {% elif record.type == "~" %}
                                        {% for change in record.changes %}
                                            <p>
                                                {% blocktrans with field=change.field old=change.old new=change.new %}{{ field }} changed from {{ old }} to {{ new }}{% endblocktrans %}
                                            </p>
                                        {% endfor %}
                                    {% else %}
                                        {% trans 'History could not be parsed!' %}
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </section>
            <footer class="mdc-dialog__actions">
                <button type="button" class="mdc-button mdc-dialog__button" title="{% trans 'Close' %}" data-mdc-dialog-action="close">{% trans 'Close' %}</button>
            </footer>
        </div>
    </div>
</div>