pyVerein/app/urls.py
# Import django-urls.
from django.urls import path
# Import views.
from . import views

# Set app name
app_name = 'app'
# Set url-patterns
urlpatterns = [
    path('', views.index, name='index'),
]

pyVerein/finance/urls.py
# Import django-urls.
from django.urls import path
# Import views.
from . import views

# Set app name
app_name = 'finance'
# Set url-patterns
urlpatterns = [
    path('creditor/', views.CreditorIndexView.as_view(), name='creditor_list'),
    path('creditor/new/', views.CreditorCreateView.as_view(), name='creditor_create'),
    path('creditor/<str:pk>/', views.CreditorDetailView.as_view(), name='creditor_detail'),
    path('creditor/<str:pk>/edit/', views.CreditorEditView.as_view(), name='creditor_edit'),
    path('creditor/<str:account>/clearing/', views.CreditorClearingView.as_view(), name='creditor_clear'),

    path('debitor/', views.DebitorIndexView.as_view(), name='debitor_list'),
    path('debitor/new/', views.DebitorCreateView.as_view(), name='debitor_create'),
    path('debitor/<str:pk>/', views.DebitorDetailView.as_view(), name='debitor_detail'),
    path('debitor/<str:pk>/edit/', views.DebitorEditView.as_view(), name='debitor_edit'),
    path('debitor/<str:account>/clearing/', views.DebitorClearingView.as_view(), name='debitor_clear'),

    path('impersonal/', views.ImpersonalIndexView.as_view(), name='impersonal_list'),
    path('impersonal/new/', views.ImpersonalCreateView.as_view(), name='impersonal_create'),
    path('impersonal/<str:pk>/', views.ImpersonalDetailView.as_view(), name='impersonal_detail'),
    path('impersonal/<str:pk>/edit/', views.ImpersonalEditView.as_view(), name='impersonal_edit'),

    path('costcenter/', views.CostCenterIndexView.as_view(), name='costcenter_list'),
    path('costcenter/new/', views.CostCenterCreateView.as_view(), name='costcenter_create'),
    path('costcenter/<str:pk>/', views.CostCenterDetailView.as_view(), name='costcenter_detail'),
    path('costcenter/<str:pk>/edit/', views.CostCenterEditView.as_view(), name='costcenter_edit'),

    path('costobject/', views.CostObjectIndexView.as_view(), name='costobject_list'),
    path('costobject/new/', views.CostObjectCreateView.as_view(), name='costobject_create'),
    path('costobject/<str:pk>/', views.CostObjectDetailView.as_view(), name='costobject_detail'),
    path('costobject/<str:pk>/edit/', views.CostObjectEditView.as_view(), name='costobject_edit'),

    path('transaction/', views.TransactionIndexView.as_view(), name='transaction_list'),
    path('transaction/new/', views.TransactionCreateView.as_view(), name='transaction_create'),
    path('transaction/new/<str:session_id>/', views.TransactionCreateView.as_view(), name='transaction_create_session'),
    path('transaction/new/<str:session_id>/<int:step>/', views.TransactionCreateView.as_view(), name='transaction_create_step'),
    path('transaction/<int:internal_number>/', views.TransactionDetailView.as_view(), name='transaction_detail'),
    path('transaction/<int:internal_number>/edit/<int:pk>/', views.TransactionEditView.as_view(), name='transaction_edit'),
    path('transaction/<int:internal_number>/reset', views.reset_transaction, name='transaction_reset'),
    path('transaction/<int:internal_number>/reset_new', views.reset_new_transaction, name='transaction_reset_new'),

    path('virtual_account/', views.VirtualAccountIndexView.as_view(), name='virtual_account_list'),
    path('virtual_account/new/', views.VirtualAccountCreateView.as_view(), name='virtual_account_create'),
    path('virtual_account/<str:pk>/', views.VirtualAccountDetailView.as_view(), name='virtual_account_detail'),
    path('virtual_account/<str:pk>/edit/', views.VirtualAccountEditView.as_view(), name='virtual_account_edit'),

    path('api/account/<str:search>', views.get_account, name='account_search'),
    path('api/costcenter/<str:search>', views.get_cost_center, name='costcenter_search'),
    path('api/costobject/<str:search>', views.get_cost_object, name='costobject_search'),
    path('api/clearing/', views.clear_transaction, name='clear_transactions'),
    path('api/clearing/reset/', views.reset_cleared_transaction, name='reset_cleared_transactions'),
] 

pyVerein/finance/models.py
from django.db import models
# Import localization
from django.utils.translation import ugettext_lazy as _
from author.decorators import with_author
from django.db.models import Q
from utils.models import ModelBase

@with_author
class Account(ModelBase):
    """
    Account model.
    """
    class Meta:
        permissions = (
            ('view_creditor', "Can view creditor"),
            ('add_creditor', "Can add creditor"),
            ('change_creditor', "Can change creditor"),
            ('view_debitor', "Can view debitor"),
            ('add_debitor', "Can add debitor"),
            ('change_debitor', "Can change debitor"),
            ('view_impersonal', "Can view impersonal"),
            ('add_impersonal', "Can add impersonal"),
            ('change_impersonal', "Can change impersonal"),
        )

    # Choices for account type
    CREDITOR = 'CRE'
    DEBITOR = 'DEB'
    COST = 'COS'
    INCOME = 'INC'
    ASSET = 'ASS'
    ACCOUNT_TYPES = (
        (CREDITOR, _('Creditor')),
        (DEBITOR, _('Debitor')),
        (COST, _('Cost')),
        (INCOME, _('Income')),
        (ASSET, _('Asset'))
    )
    # Account number
    number = models.CharField(max_length=10, blank=False, null=False, unique=True, primary_key=True)
    # Account name
    name = models.CharField(max_length=255, blank=False, null=False)
    # Account type: debitor/creditor/cost/income
    account_type = models.CharField(blank=False, null=False, choices=ACCOUNT_TYPES, max_length=3, default=COST)

@with_author
class CostCenter(ModelBase):
    """
    Cost center model
    """
    # Cost center number
    number = models.CharField(max_length=10, blank=False, null=False, unique=True, primary_key=True)
    # Cost center name
    name = models.CharField(max_length=255, blank=False, null=False)
    # Description
    description = models.TextField(blank=True, null=True)

@with_author
class CostObject(ModelBase):
    """
    Cost object model
    """
    # Cost object number
    number = models.CharField(max_length=10, blank=False, null=False, unique=True, primary_key=True)
    # Cost object name
    name = models.CharField(max_length=255, blank=False, null=False)
    # Description
    description = models.TextField(blank=True, null=True)

@with_author
class Transaction(ModelBase):
    """
    Transaction model.
    """
    # Account
    account = models.ForeignKey(Account, on_delete=models.PROTECT)

    # Transaction date
    date = models.DateField(null=False, blank=False)
    # Document number
    document_number = models.CharField(max_length=255, blank=True, null=True)
    # Transaction text
    text = models.CharField(max_length=255, blank=False, null=False)

    # Debit value
    debit = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    # Credit value
    credit = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)

    # Cost center
    cost_center = models.ForeignKey(CostCenter, on_delete=models.PROTECT, blank=True, null=True)
    # Cost object
    cost_object = models.ForeignKey(CostObject, on_delete=models.PROTECT, blank=True, null=True)

    # Is document_number generated
    document_number_generated = models.BooleanField(default=False)
    # Internal number to keep connection of transactions
    internal_number = models.IntegerField(null=False, blank=False, default=0)
    # Is transaction reset
    reset = models.BooleanField(blank=False, null=False, default=False)
    # Clearing Number
    clearing_number = models.IntegerField(null=True, blank=True)
    # Accounting year
    accounting_year = models.IntegerField(blank=True, null=True)

    def is_cleared(self):
        """
        Returns whether the transaction was cleared
        """
        for transaction in Transaction.objects.filter((Q(account__account_type=Account.DEBITOR) | Q(account__account_type=Account.CREDITOR)) & Q(internal_number=self.internal_number)):
            if not transaction.clearing_number:
                return False

        return True

@with_author
class ClosureTransaction(ModelBase):
    """
    Transaction model for annual closure.
    """
    # Account number
    account_number = models.CharField(max_length=10, blank=False, null=False)
    # Account name
    account_name = models.CharField(max_length=255, blank=False, null=False)

    # Transaction date
    date = models.DateField(null=False, blank=False)
    # Document number
    document_number = models.CharField(max_length=255, blank=True, null=True)
    # Transaction text
    text = models.CharField(max_length=255, blank=False, null=False)

    # Debit value
    debit = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    # Credit value
    credit = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)

    # Cost center number
    cost_center_number = models.CharField(max_length=10, blank=True, null=True)
    # Cost center name
    cost_center_name = models.CharField(max_length=255, blank=True, null=True)
    # Description
    cost_center_description = models.TextField(blank=True, null=True)

    # Cost object number
    cost_object_number = models.CharField(max_length=10, blank=True, null=True)
    # Cost object name
    cost_object_name = models.CharField(max_length=255, blank=True, null=True)
    # Description
    cost_object_description = models.TextField(blank=True, null=True)

    # Is document_number generated
    document_number_generated = models.BooleanField(default=False)
    # Internal number to keep connection of transactions
    internal_number = models.IntegerField(null=False, blank=False, default=0)
    # Is transaction reset
    reset = models.BooleanField(blank=False, null=False, default=False)
    # Clearing Number
    clearing_number = models.IntegerField(null=True, blank=True)
    # Accounting year
    accounting_year = models.IntegerField(blank=True, null=True)

@with_author
class ClosureBalance(ModelBase):
    """
    Model for balances at closure
    """

    # Closure year
    year = models.IntegerField(blank=True, null=True, unique=True)

    # Claims at end of year
    claims = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)

    # Liabilities at end of year
    liabilities = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)

@with_author
class VirtualAccount(ModelBase):
    """
    Virtual account model
    """
    # Virtual account number
    number = models.CharField(max_length=10, blank=False, null=False, unique=True, primary_key=True)
    # Virtual account name
    name = models.CharField(max_length=255, blank=False, null=False)

    # Initial value
    initial = models.DecimalField(max_digits=12, decimal_places=2, blank=False, null=False)
    # Active from
    active_from = models.DateField(null=False, blank=False)
    # Costcenter
    cost_center = models.CharField(max_length=255, blank=True, null=True)
    # Costobjects
    cost_objects = models.CharField(max_length=255, blank=True, null=True)

pyVerein/finance/forms.py
"""
Formmodule for finnaceapp
"""
# Import Forms
from django import forms
# Import localization
from django.utils.translation import ugettext_lazy as _
# Import Accountmodel
from .models import Account, CostCenter, CostObject, Transaction, VirtualAccount

class PersonalAccountCreateForm(forms.ModelForm):
    """
    Formclass for creating debitors & creditors
    """
    class Meta:
        """
        Form metadata
        """
        model = Account
        fields = ('number', 'name')

class PersonalAccountEditForm(forms.ModelForm):
    """
    Formclass for editing debitors & creditors
    """
    class Meta:
        """
        Form metadata
        """
        model = Account
        fields = ('name',)

class ImpersonalAccountCreateForm(forms.ModelForm):
    """
    Formclass for creating impersonal accounts
    """
    class Meta:
        """
        Form metadata
        """
        model = Account
        fields = ('number', 'name', 'account_type')
        widgets = {
            'account_type': forms.RadioSelect(attrs={'class':'mdc-radio__native-control'})
        }
    
    def __init__(self, *args, **kwargs):
        """
        Init form with type choices
        """
        TYPES = (
            (Account.COST, _('Cost')),
            (Account.INCOME, _('Income')),
            (Account.ASSET, _('Asset'))
        )
        super(ImpersonalAccountCreateForm, self).__init__(*args, **kwargs)
        self.fields['account_type'].choices = TYPES

class ImpersonalAccountEditForm(forms.ModelForm):
    """
    Formclass for editing impersonal accounts
    """
    class Meta:
        """
        Form metadata
        """
        model = Account
        fields = ('name', )


class CostCenterCreateForm(forms.ModelForm):
    """
    Formclass for costcenters
    """
    class Meta:
        """
        Form metadata
        """
        model = CostCenter
        fields = ('number', 'name', 'description')

class CostCenterEditForm(forms.ModelForm):
    """
    Formclass for costcenters
    """
    class Meta:
        """
        Form metadata
        """
        model = CostCenter
        fields = ('name', 'description')

class CostObjectCreateForm(forms.ModelForm):
    """
    Formclass for costobjects
    """
    class Meta:
        """
        Form metadata
        """
        model = CostObject
        fields = ('number', 'name', 'description')

class CostObjectEditForm(forms.ModelForm):
    """
    Formclass for costobjects
    """
    class Meta:
        """
        Form metadata
        """
        model = CostObject
        fields = ('name', 'description')

class TransactionCreateForm(forms.ModelForm):
    """
    Formclass for transactions
    """
    class Meta:
        """
        Form metadata
        """
        model = Transaction
        fields = ('account', 'date', 'document_number', 'text', 'debit', 'credit', 'cost_center', 'cost_object')
        localized_fields = ('debit', 'credit')
        widgets = {
            'account': forms.TextInput(),
            'debit': forms.TextInput(),
            'credit': forms.TextInput(),
            'cost_center': forms.TextInput(),
            'cost_object': forms.TextInput(),
        }

class TransactionEditForm(forms.ModelForm):
    """
    Formclass for transactions
    """
    class Meta:
        """
        Form metadata
        """
        model = Transaction
        fields = ('text', 'cost_center', 'cost_object')
        widgets = {
            'cost_center': forms.TextInput(),
            'cost_object': forms.TextInput(),
        }

class VirtualAccountCreateForm(forms.ModelForm):
    """
    Formclass for creating virtual accounts
    """
    class Meta:
        """
        Form metadata
        """
        model = VirtualAccount
        fields = ('number', 'name', 'initial', 'active_from', 'cost_center', 'cost_objects')
        localized_fields = ('initial',)
        widgets = {
            'initial': forms.TextInput(),
            'cost_center': forms.TextInput(),
            'cost_object': forms.TextInput(),
        }
       
class VirtualAccountEditForm(forms.ModelForm):
    """
    Formclass for editing virtual accounts
    """
    class Meta:
        """
        Form metadata
        """
        model = VirtualAccount
        fields = ('name', 'initial', 'active_from', 'cost_center', 'cost_objects')
        localized_fields = ('initial',)
        widgets = {
            'initial': forms.TextInput(),
            'cost_center': forms.TextInput(),
            'cost_object': forms.TextInput(),
        }

pyVerein/finance/templates/finance/transaction/detail.html
{% extends 'app/base.html' %}
{% load i18n %}
{% load static %}

{% block head %}
    <!-- DataTables -->
    <link rel="stylesheet" href="{% static 'app/vendors/datatables.net/material.min.css' %}">
    <link rel="stylesheet" href="{% static 'app/vendors/datatables.net/datatables.material.min.css' %}">
    
{% endblock %}

{% block page_title %}
    {% trans 'Receipt-Detail' %}
{% endblock %}

{% block title %}
    {% trans 'Receipt-Detail' %}
{% endblock %}

{% block content %}
    <div class="mdc-dialog" id="reset-dialog">
        <div class="mdc-dialog__scrim"></div>
        <div class="mdc-dialog__container">
            <div class="mdc-dialog__surface">
                <h2 class="mdc-dialog__title">{% trans 'Reset clearing' %}</h2>
                <section class="mdc-dialog__content">
                    {% trans 'Do you really want to reset this clearing?' %}
                </section>
                <footer class="mdc-dialog__actions">
                    <button type="button" class="mdc-button mdc-dialog__button" title="{% trans 'Cancel' %}" data-mdc-dialog-action="close">{% trans 'Cancel' %}</button>
                    <button type="button" class="mdc-button mdc-button" id="reset_button" title="{% trans 'Reset' %}">{% trans 'Reset clearing' %}</button>
                </footer>
            </div>
        </div>
    </div>
    <div class="main">
        <div class="detail-content mdc-elevation--z4">
            <div class="heading mdc-typography--overline">
                {% trans 'General' %}
            </div>
            <div class="row">
                <div class="field-title">{% trans 'Date' %}</div>
                <div class="field-value">{{ date|default_if_none:"" }}</div>
            </div>
            <div class="row">
                <div class="field-title">{% trans 'Document number' %}</div>
                <div class="field-value">{{ document_number|default_if_none:"" }}</div>
            </div>
        
            <div class="heading mdc-typography--overline">
                {% trans 'Transactions' %}
            </div>
            <div class="row">
                <table id="transactions" class="mdl-data-table mdl-js-data-table" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th class="mdl-data-table__cell--non-numeric">{% trans 'Account' %}</th>
                            <th class="mdl-data-table__cell--non-numeric">{% trans 'Transaction text' %}</th>
                            <th>{% trans 'Debit' %}</th>
                            <th>{% trans 'Credit' %}</th>
                            <th>{% trans 'Cost center' %}</th>
                            <th>{% trans 'Cost object' %}</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for transaction in transactions %}
                            <tr>
                                <td class="mdl-data-table__cell--non-numeric">
                                    {% if transaction.account.account_type == 'DEB' %}
                                        <a href="{% url 'finance:debitor_detail' pk=transaction.account.number %}" title="{% trans 'Show Account' %}" target="_blank">
                                            {{ transaction.account.number }}
                                        </a>
                                    {% endif %}
                                    {% if transaction.account.account_type == 'CRE' %}
                                        <a href="{% url 'finance:creditor_detail' pk=transaction.account.number %}" title="{% trans 'Show Account' %}" target="_blank">
                                            {{ transaction.account.number }}
                                        </a>
                                    {% endif %}
                                    {% if transaction.account.account_type == 'COS' or transaction.account.account_type == 'INC' or transaction.account.account_type == 'ASS' %}
                                        <a href="{% url 'finance:impersonal_detail' pk=transaction.account.number %}" title="{% trans 'Show Account' %}" target="_blank">
                                            {{ transaction.account.number }}
                                        </a>
                                    {% endif %}
                                </td>
                                <td class="mdl-data-table__cell--non-numeric">
                                    {{ transaction.text }}
                                </td>
                                <td>
                                    {{ transaction.debit|default_if_none:"" }}
                                </td>
                                <td>
                                    {{ transaction.credit|default_if_none:"" }}
                                </td>
                                <td>
                                    {% if transaction.cost_center.number %}
                                        <a href="{% url 'finance:costcenter_detail' pk=transaction.cost_center.number %}" title="{% trans 'Show cost center' %}" target="_blank">
                                            {{ transaction.cost_center.number }}
                                        </a>
                                    {% endif %}
                                </td>
                                <td>
                                        {% if transaction.cost_object.number %}
                                        <a href="{% url 'finance:costobject_detail' pk=transaction.cost_object.number %}" title="{% trans 'Show cost object' %}" target="_blank">
                                            {{ transaction.cost_object.number }}
                                        </a>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            {% if cleared_transactions %}
                <div class="heading mdc-typography--overline">
                    {% trans 'Cleared transactions' %}
                </div>
                <div class="row">
                    <table id="cleared-transactions" class="mdl-data-table mdl-js-data-table" cellspacing="0" width="100%">
                        <thead>
                            <tr>
                                <th class="mdl-data-table__cell--non-numeric">{% trans 'Account' %}</th>
                                <th class="mdl-data-table__cell--non-numeric">{% trans 'Document number' %}</th>
                                <th class="mdl-data-table__cell--non-numeric">{% trans 'Transaction text' %}</th>
                                <th>{% trans 'Debit' %}</th>
                                <th>{% trans 'Credit' %}</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for transaction in cleared_transactions %}
                                <tr>
                                    <td class="mdl-data-table__cell--non-numeric">
                                        {{ transaction.account.number }}
                                    </td>
                                    <td class="mdl-data-table__cell--non-numeric">
                                        <a href="{% url 'finance:transaction_detail' internal_number=transaction.internal_number %}" title="{% trans 'Show receipt' %}">
                                            {{ transaction.document_number }}
                                        </a>
                                    </td>
                                    <td class="mdl-data-table__cell--non-numeric">
                                        {{ transaction.text }}
                                    </td>
                                    <td>
                                        {{ transaction.debit|default_if_none:"" }}
                                    </td>
                                    <td>
                                        {{ transaction.credit|default_if_none:"" }}
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            {% endif %}
        </div>
    </div>
    {% if perms.finance.change_transaction %}
    <a href ="{% url 'finance:transaction_edit' internal_number=internal_number pk=transactions.0.pk%}" class="mdc-fab mdc-fab--absolute-bottom-right" aria-label="" title="{% trans 'Edit' %}">
        <i class="mdc-fab__icon fa fa-pencil-alt"></i>
    </a>
    {% endif %}
    {% if cleared_transactions %}
        <a href="#" id="btn-reset-clearing" class="mdc-fab mdc-fab--absolute-bottom-right second" aria-label="" title="{% trans 'Reset clearing' %}">
            <i class="mdc-fab__icon fa fa-eraser"></i>
        </a>
    {% endif %}
{% endblock %}

{% block foot %}{% if cleared_transactions %}
        <script>
            $(document).ready(function () {
                const reset_dialog = new mdc.dialog.MDCDialog(document.querySelector('#reset-dialog'));
                $('#reset_dialog_button').click(function() {
                });
                
                $('#reset_button').click(function() {
                    $.post("{% url 'finance:reset_cleared_transactions' %}", {"clearing_number": {{ clearing_number }}}, function (){
                        location.reload();
                    }, "json");
                });
                $.ajaxSetup({ 
                    beforeSend: function(xhr, settings) {
                        xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
                    } 
                });
                $("#btn-reset-clearing").click(function (){
                    reset_dialog.open();
                });
            });
            
            function getCookie(name){
                var cookieValue = null;
                if (document.cookie && document.cookie != '') {
                    var cookies = document.cookie.split(';');
                    for (var i = 0; i < cookies.length; i++) {
                        var cookie = jQuery.trim(cookies[i]);
                        // Does this cookie string begin with the name we want?

                        if (cookie.substring(0, name.length + 1) == (name + '=')) {
                            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                            break;
                        }
                    }
                }
                return cookieValue;
            }
        </script>
    {% endif %}
{% endblock foot %}