pyVerein/app/urls.py
# Import django-urls.
from django.urls import path
# Import views.
from . import views

# Set app name
app_name = 'app'
# Set url-patterns
urlpatterns = [
    path('', views.index, name='index'),
]

pyVerein/members/urls.py
# Import django-urls.
from django.urls import path
# Import views.
from . import views

# Set app name
app_name = 'members'
# Set url-patterns
urlpatterns = [
    path('member/', views.MemberIndexView.as_view(), name='member_list'),
    path('member/new/', views.MemberCreateView.as_view(), name='member_create'),
    path('member/<int:pk>/', views.MemberDetailView.as_view(), name='member_detail'),
    path('member/edit/<int:pk>/', views.MemberEditView.as_view(), name='member_edit'),
    path('upload_file/<int:pk>/', views.upload_file, name='member_upload_file'),
    path('delete_file/<int:pk>/', views.delete_file, name='member_delete_file'),
    path('download_file/<int:pk>/', views.download_file, name='member_download_file'),

    path('division/', views.DivisionIndexView.as_view(), name='division_list'),
    path('division/new/', views.DivisionCreateView.as_view(), name='division_create'),
    path('division/<int:pk>/', views.DivisionDetailView.as_view(), name='division_detail'),
    path('division/edit/<int:pk>/', views.DivisionEditView.as_view(), name='division_edit'),

    path('subscription/', views.SubscriptionIndexView.as_view(), name='subscription_list'),
    path('subscription/new/', views.SubscriptionCreateView.as_view(), name='subscription_create'),
    path('subscription/<int:pk>/', views.SubscriptionDetailView.as_view(), name='subscription_detail'),
    path('subscription/edit/<int:pk>/', views.SubscriptionEditView.as_view(), name='subscription_edit'),
]

pyVerein/members/models.py
from django.db import models
# Import localization
from django.utils.translation import ugettext_lazy as _
# Import datetime
from datetime import datetime
from finance.models import Account, CostCenter, CostObject
from dynamic_preferences.registries import global_preferences_registry
from utils.models import AccessRestrictedModel, ModelBase
import uuid
from author.decorators import with_author

# Member model.
@with_author
class Member(ModelBase):
    class Meta:
        permissions = ( 
            ('view_field_salutation', 'Can view field salutation'),
            ('view_field_last_name', 'Can view field last_name'),
            ('view_field_first_name', 'Can view field first_name'),
            ('view_field_street', 'Can view field street'),
            ('view_field_zipcode', 'Can view field zipcode'),
            ('view_field_city', 'Can view field city'),
            ('view_field_birthday', 'Can view field birthday'),
            ('view_field_phone', 'Can view field phone'),
            ('view_field_mobile', 'Can view field mobile'),
            ('view_field_fax', 'Can view field fax'),
            ('view_field_email', 'Can view field email'),
            ('view_field_membership_number', 'Can view field membership number'),
            ('view_field_joined_at', 'Can view field joined at'),
            ('view_field_terminated_at', 'Can view field terminated at'),
            ('view_field_division', 'Can view field division'),
            ('view_field_payment_method', 'Can view field payment method'),
            ('view_field_iban', 'Can view field iban'),
            ('view_field_bic', 'Can view field bic'),
            ('view_field_debit_mandate_at', 'Can view field debit mandate at'),
            ('view_field_debit_reference', 'Can view field debit reference'),
            ('view_field_subscription', 'Can view field subscription'),
            ('view_field_field_1', 'Can view field field 1'),
            ('view_field_field_2', 'Can view field field 2'),
            ('view_field_field_3', 'Can view field field 3'),
            ('view_field_field_4', 'Can view field field 4'),
            ('view_field_field_5', 'Can view field field 5'),
            ('view_files', 'Can view files')
        )

    # Choices for salutation
    MR = 'MR'
    MRS = 'MRS'
    SALUTATIONS = (
        (MR, _('Mr.')),
        (MRS, _('Mrs.'))
    )
    # Salutation
    salutation = models.CharField(blank=False, null=False, choices=SALUTATIONS, max_length=3, default=MR)
    # Lastname
    last_name = models.CharField(blank=False, null=False, max_length=50)
    # Firstname
    first_name = models.CharField(blank=False, null=False, max_length=50)

    # Street
    street = models.CharField(blank=True, null=True, max_length=200)
    # Zipcode
    zipcode = models.CharField(blank=True, null=True, max_length=10)
    # City
    city = models.CharField(blank=True, null=True, max_length=100)

    # Birthday
    birthday = models.DateField(blank=True, null=True)

    # Phone
    phone = models.CharField(blank=True, null=True, max_length=20)
    # mobile
    mobile = models.CharField(blank=True, null=True, max_length=20)
    # fax
    fax = models.CharField(blank=True, null=True, max_length=20)
    # email
    email = models.CharField(blank=True, null=True, max_length=255)

    # Membership number
    membership_number = models.CharField(blank=True, null=True, max_length=100)
    # Joined at
    joined_at = models.DateField(blank=True, null=True)
    # Terminated at
    terminated_at = models.DateField(blank=True, null=True)
    # Division
    division = models.ManyToManyField('Division', blank=True)

    # Choices for payment method
    CASH = 'CA'
    REMITTANCE = 'RE'
    DEBIT = 'DE'
    PAYMENT_METHODS = (
        (CASH, _('Cash')),
        (REMITTANCE, _('Remittance')),
        (DEBIT, _('Direct Debit'))
    )
    # Payment method
    payment_method = models.CharField(choices=PAYMENT_METHODS, max_length=2, default=DEBIT)
    # IBAN
    iban = models.CharField(blank=True, null=True, max_length=34)
    # BIC
    bic = models.CharField(blank=True, null=True, max_length=11)
    # Direct debit mandate granted at
    debit_mandate_at = models.DateField(blank=True, null=True)
    # Direct debit reference
    debit_reference = models.CharField(blank=True, null=True, max_length=100)
    # Subscription
    subscription = models.ManyToManyField('Subscription', blank=True)

    # Additional field 1
    field_1 = models.CharField(blank=True, null=True, max_length=255)
    # Additional field 2
    field_2 = models.CharField(blank=True, null=True, max_length=255)
    # Additional field 3
    field_3 = models.CharField(blank=True, null=True, max_length=255)
    # Additional field 4
    field_4 = models.CharField(blank=True, null=True, max_length=255)
    # Additional field 5
    field_5 = models.CharField(blank=True, null=True, max_length=255)

    uuid = models.UUIDField(default=uuid.uuid4, editable=False)

    subscriptions = models.CharField(blank=True, null=True, max_length=255)
    files = models.CharField(blank=True, null=True, max_length=255)
    divisions = models.CharField(blank=True, null=True, max_length=255)

    # Return full name
    def get_full_name(self):
        return '{0} {1}'.format(self.first_name, self.last_name)

    # Return true if membership is terminated
    def is_terminated(self):
        if self.terminated_at is not None:
            return self.terminated_at <= datetime.now().date()
        else:
            return False

    # Return full name as string representation
    def __str__(self):
        return self.get_full_name()

def get_file_path(instance, filename):
    """
    Return filepath with member id folder
    """
    return "protected/members/{}/file/{}".format(instance.member.uuid, filename)

@with_author
class File(ModelBase):
    """
    Model for member-files
    """
    member = models.ForeignKey(Member, on_delete=models.CASCADE)

    file = models.FileField(null=False, blank=False, upload_to=get_file_path)

@with_author
class Division(AccessRestrictedModel, ModelBase):
    """
    Division model
    """

    # Name
    name = models.CharField(blank=False, null=False, max_length=255)

    def __str__(self):
        return self.name

@with_author
class Subscription(ModelBase):
    """
    Subscription model
    """

    MONTHLY = 'MON'
    QUARTERLY = 'QUA'
    HALFYEARLY = 'HAL'
    YEARLY = 'YEA'
    ONCE = 'ONE'
    PAYMENT_FREQUENCY = (
        (ONCE, _('Once')),
        (MONTHLY, _('Monthly')),
        (QUARTERLY, _('Quarterly')),
        (HALFYEARLY, _('Half-Yearly')),
        (YEARLY, _('Yearly')),
    )

    # Name
    name = models.CharField(blank=False, null=False, max_length=255)
    # Amount
    amount = models.DecimalField(blank=False, null=False, max_digits=12, decimal_places=2)
    # Payment frequency
    payment_frequency = models.CharField(choices=PAYMENT_FREQUENCY, max_length=3, default=YEARLY)

    income_account = models.ForeignKey(Account, blank=True, null=True, on_delete=models.PROTECT, related_name='+')
    debitor_account = models.ForeignKey(Account, blank=True, null=True, on_delete=models.PROTECT, related_name='+')
    cost_center = models.ForeignKey(CostCenter, blank=True, null=True, on_delete=models.PROTECT, related_name='+')
    cost_object = models.ForeignKey(CostObject, blank=True, null=True, on_delete=models.PROTECT, related_name='+')

    def get_income_account(self):
        """
        Returns the assigned income account, if set, otherwise the global default
        """
        if self.income_account:
            return self.income_account
        else:
            global_preferences = global_preferences_registry.manager()
            return CostCenter.objects.get(pk=global_preferences['Members__division_income_account'])
            
    def get_debitor_account(self):
        """
        Returns the assigned debitor account, if set, otherwise the global default
        """
        if self.debitor_account:
            return self.debitor_account
        else:
            global_preferences = global_preferences_registry.manager()
            return CostCenter.objects.get(pk=global_preferences['Members__division_debitor_account'])

    def get_cost_center(self):
        """
        Returns the assigned cost center, if set, otherwise the global default
        """
        if self.cost_center:
            return self.cost_center
        else:
            global_preferences = global_preferences_registry.manager()
            return CostCenter.objects.get(pk=global_preferences['Members__division_cost_center'])

    def get_cost_object(self):
        """
        Returns the assigned cost object, if set, otherwise the global default
        """
        if self.cost_object:
            return self.cost_object
        else:
            global_preferences = global_preferences_registry.manager()
            return CostCenter.objects.get(pk=global_preferences['Members__division_cost_object'])

    def __str__(self):
        return self.name

pyVerein/members/forms.py
from django import forms
from .models import Member, Division, Subscription
from django.forms.widgets import TextInput, CheckboxSelectMultiple

class MemberForm(forms.ModelForm):
    class Meta:
        model = Member
        fields = ('salutation', 'last_name', 'first_name', 'street', 'zipcode', 'city', 'birthday', 'phone', 'mobile', 'fax', 'email', 'membership_number', 'division', 'joined_at', 'terminated_at', 'payment_method', 'subscription', 'iban', 'bic', 'debit_mandate_at', 'debit_reference', 'field_1', 'field_2', 'field_3', 'field_4', 'field_5')
        widgets = {
            'salutation': forms.RadioSelect(attrs={'class':'mdc-radio__native-control'}),
            'subscription': forms.CheckboxSelectMultiple(attrs={'class': 'mdc-checkbox__native-control'}),
            'division': forms.CheckboxSelectMultiple(attrs={'class': 'mdc-checkbox__native-control'}),
        }

class DivisionForm(forms.ModelForm):
    class Meta:
        model = Division
        fields = ('name', 'user', 'groups')
        widgets = {
            'user': CheckboxSelectMultiple(attrs={'class': 'mdc-checkbox__native-control'}),
            'groups': CheckboxSelectMultiple(attrs={'class': 'mdc-checkbox__native-control'})
        }

class SubscriptionForm(forms.ModelForm):
    class Meta:
        model = Subscription
        fields = ('name', 'amount', 'payment_frequency', 'income_account', 'debitor_account', 'cost_center', 'cost_object',)
        widgets = {
            'amount': forms.TextInput(),
            'income_account': TextInput(),
            'debitor_account': TextInput(),
            'cost_center': TextInput(),
            'cost_object': TextInput(),
            'payment_frequency': forms.RadioSelect(attrs={'class':'mdc-radio__native-control'})
        }

pyVerein/members/templates/members/member/create.html
{% extends 'app/base.html' %}
{% load i18n %}
{% load widget_tweaks %}
{% load static %}
{% get_current_language as LANGUAGE_CODE %}

{% block head %}

{% endblock %}

{% block page_title %}
    {% trans 'Create member' %}
{% endblock %}

{% block title %}
    {% trans 'Create member' %}
{% endblock %}

{% block content %}
    <div class="main-narrow form">
        <div class="detail-content  mdc-elevation--z4">
            <form action="{% url 'members:member_create' %}" method="POST" id="form">
                {% include 'members/member/form_fields.html' %}
                <div class="form-group form-submit">
                    <input type="submit" class="mdc-button mdc-button--raised" value="{% trans 'Save' %}" title="{% trans 'Save' %}" />
                    <a href="{% url 'members:member_list' %}" class="mdc-button" title="{% trans 'Cancel' %}">{% trans 'Cancel' %}</a>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

{% block foot %}<!-- Inputmask -->
    <script src="{% static 'app/vendors/jquery.inputmask/dist/jquery.inputmask.bundle.js' %}"></script>
    <script>
        $("#id_birthday").inputmask({
            mask:"99.99.9999",
            showMaskOnHover: false,
        });
        $("#id_joined_at").inputmask({
            mask:"99.99.9999",
            showMaskOnHover: false,
        });
        $("#id_terminated_at").inputmask({
            mask:"99.99.9999",
            showMaskOnHover: false,
        });
        $("#id_debit_mandate_at").inputmask({
            mask:"99.99.9999",
            showMaskOnHover: false,
        });
        $("#id_iban").inputmask({
            mask:"{{ global_preferences.Members__iban_format }}",
            showMaskOnHover: false,
        });
    </script>
    
    <!-- Keys -->
    <script src="{% static 'app/js/keys.js' %}"></script>
    <script>
        $('#form').saveOnTimes();
        $('#form').nextOnEnter();
    </script>
{% endblock %}

pyVerein/members/templates/members/member/edit.html
{% extends 'app/base.html' %}
{% load i18n %}
{% load widget_tweaks %}
{% load static %}
{% get_current_language as LANGUAGE_CODE %}

{% block head %}

{% endblock %}

{% block page_title %}
    {% trans 'Edit member' %}
{% endblock %}

{% block title %}
    {% trans 'Edit member' %}
{% endblock %}

{% block content %}
<div class="main-narrow form">
    <div class="detail-content  mdc-elevation--z4">
        <form action="{% url 'members:member_edit' member.pk %}" method="POST" id="form">
            {% include 'members/member/form_fields.html' %}
            <div class="form-group form-submit">
                <input type="submit" class="mdc-button mdc-button--raised" value="{% trans 'Save' %}" title="{% trans 'Save' %}" />
                <a href="{% url 'members:member_detail' pk=member.pk %}" class="mdc-button" title="{% trans 'Cancel' %}">{% trans 'Cancel' %}</a>
            </div>
        </form>
    </div>
</div>
   
{% endblock %}

{% block foot %}<!-- Inputmask -->
    <script src="{% static 'app/vendors/jquery.inputmask/dist/jquery.inputmask.bundle.js' %}"></script>
    <script>
        $("#id_birthday").inputmask({
            mask:"99.99.9999",
            showMaskOnHover: false,
        });
        $("#id_joined_at").inputmask({
            mask:"99.99.9999",
            showMaskOnHover: false,
        });
        $("#id_terminated_at").inputmask({
            mask:"99.99.9999",
            showMaskOnHover: false,
        });
        $("#id_debit_mandate_at").inputmask({
            mask:"99.99.9999",
            showMaskOnHover: false,
        });
        $("#id_iban").inputmask({
            mask:"{{ global_preferences.Members__iban_format }}",
            showMaskOnHover: false,
        });
    </script>
    
    <!-- Keys -->
    <script src="{% static 'app/js/keys.js' %}"></script>
    <script>
        $('#form').saveOnTimes();
        $('#form').nextOnEnter();
    </script>
{% endblock %}

pyVerein/members/templates/members/member/form_fields.html
{% load i18n %}
{% load widget_tweaks %}

{% csrf_token %}
<div class="heading mdc-typography--overline">
    {% trans 'Personal Data' %}
</div>
<div class="form-group">
    {% for radio in form.salutation %}
        {% include "utils/_radio.html" with radio=radio %}
    {% endfor %}
</div>
<div class="form-group">
    {% trans 'Firstname' as first_name_label%}
    {% include "utils/_textfield.html" with field=form.first_name label=first_name_label next='id_last_name' %}

    {% trans 'Lastname' as last_name_label%}
    {% include "utils/_textfield.html" with field=form.last_name label=last_name_label next='id_birthday' %}
</div>
<div class="form-group">
    {% trans 'Birthday' as birthday_label%}
    {% include "utils/_textfield.html" with field=form.birthday label=birthday_label next='id_street' %}
    <div class="spacer">&nbsp;</div>
</div>

<div class="heading mdc-typography--overline">
    {% trans 'Address' %}
</div>
<div class="form-group">
    {% trans 'Street' as street_label%}
    {% include "utils/_textfield.html" with field=form.street label=street_label next='id_zipcode' %}
    <div class="spacer">&nbsp;</div>
</div>
<div class="form-group">
    {% trans 'Zip-Code' as zipcode_label%}
    {% include "utils/_textfield.html" with field=form.zipcode label=zipcode_label next='id_city' %}

    {% trans 'City' as city_label%}
    {% include "utils/_textfield.html" with field=form.city label=city_label next='id_phone' %}
</div>

<div class="heading mdc-typography--overline">
    {% trans 'Contact' %}
</div>
<div class="form-group">
    {% trans 'Phone' as phone_label%}
    {% include "utils/_textfield.html" with field=form.phone label=phone_label next='id_mobile' %}
   
    {% trans 'Mobile' as mobile_label%}
    {% include "utils/_textfield.html" with field=form.mobile label=mobile_label next='id_email' %}
</div>
<div class="form-group">
    {% trans 'Email' as email_label%}
    {% include "utils/_textfield.html" with field=form.email label=email_label next='id_fax' %}
    <div class="spacer">&nbsp;</div>
</div>
<div class="form-group">
    {% trans 'Fax' as fax_label%}
    {% include "utils/_textfield.html" with field=form.fax label=fax_label next='id_membership_number' %}
    <div class="spacer">&nbsp;</div>
</div>

<div class="heading mdc-typography--overline">
    {% trans 'Membership' %}
</div>
<div class="form-group">
    {% trans 'Membership number' as membership_number_label%}
    {% include "utils/_textfield.html" with field=form.membership_number label=membership_number_label next='id_division' %}
    <div class="spacer">&nbsp;</div>
</div>
<div class="form-group">
    {% trans 'Joined at' as joined_at_label%}
    {% include "utils/_textfield.html" with field=form.joined_at label=joined_at_label next='id_terminated_at' %}

    {% trans 'Terminated at' as terminated_at_label%}
    {% include "utils/_textfield.html" with field=form.terminated_at label=terminated_at_label next='id_subscription' %}
</div>
<div class="heading mdc-typography--overline">
    {% trans 'Division' %}
</div>
<div class="form-group">
    {% include "utils/_checkboxmultipleselect.html" with field=form.division next='id_subscription' %}
</div>
<div class="heading mdc-typography--overline">
    {% trans 'Subscription' %}
</div>
<div class="form-group">
    {% include "utils/_checkboxmultipleselect.html" with field=form.subscription next='id_payment_method' %}
</div>

<div class="heading mdc-typography--overline">
    {% trans 'Payment' %}
</div>
<div class="form-group">
    {% trans 'Method' as method_label%}
    {% include "utils/_select.html" with field=form.payment_method label=method_label next='id_iban' %}
</div>

<div class="form-group">
    {% trans 'IBAN' as iban_label%}
    {% include "utils/_textfield.html" with field=form.iban label=iban_label next='id_bic' %}

    {% trans 'BIC' as bic_label%}
    {% include "utils/_textfield.html" with field=form.bic label=bic_label next='id_debit_mandate_at' %}
</div>
<div class="form-group">
    {% trans 'Direct debit mandate granted at' as debit_mandate_at_label%}
    {% include "utils/_textfield.html" with field=form.debit_mandate_at label=debit_mandate_at_label next='id_debit_reference' %}

    {% trans 'Direct debit reference' as debit_reference_label%}
    {% include "utils/_textfield.html" with field=form.debit_reference label=debit_reference_label %}
</div>


{% if global_preferences.Members__show_additional_field_1 or global_preferences.Members__show_additional_field_2 or global_preferences.Members__show_additional_field_3 or global_preferences.Members__show_additional_field_4 or global_preferences.Members__show_additional_field_5 %}
<div class="heading mdc-typography--overline">
    {% trans 'Additional Information' %}
</div>
{% endif %}
{% if global_preferences.Members__show_additional_field_1 %}
<div class="form-group">
    {% trans 'Additional field 1' as field_1_label%}
    {% include "utils/_textfield.html" with field=form.field_1 label=field_1_label %}
</div>
{% endif %}
{% if global_preferences.Members__show_additional_field_2 %}
<div class="form-group">
    {% trans 'Additional field 2' as field_2_label%}
    {% include "utils/_textfield.html" with field=form.field_2 label=field_2_label %}
</div>
{% endif %}
{% if global_preferences.Members__show_additional_field_3 %}
<div class="form-group">
    {% trans 'Additional field 3' as field_3_label%}
    {% include "utils/_textfield.html" with field=form.field_3 label=field_3_label %}
</div>
{% endif %}
{% if global_preferences.Members__show_additional_field_4 %}
<div class="form-group">
    {% trans 'Additional field 4' as field_4_label%}
    {% include "utils/_textfield.html" with field=form.field_4 label=field_4_label %}
</div>
{% endif %}
{% if global_preferences.Members__show_additional_field_5 %}
<div class="form-group">
    {% trans 'Additional field 5' as field_5_label%}
    {% include "utils/_textfield.html" with field=form.field_5 label=field_5_label %}
</div>
{% endif %}

pyVerein/members/templates/members/member/list.html
{% extends 'app/base.html' %}
{% load i18n %}
{% load staticfiles %}

{% block head %}
    <!-- DataTables -->
    <link rel="stylesheet" href="{% static 'app/vendors/datatables.net/material.min.css' %}">
    <link rel="stylesheet" href="{% static 'app/vendors/datatables.net/datatables.material.min.css' %}">
{% endblock %}

{% block page_title %}
    {% trans 'Member-List' %}
{% endblock %}

{% block title %}
    {% trans 'Member-List' %}
{% endblock %}

{% block content %}
    <table id="memberslist" class="mdl-data-table dataTable"
        cellspacing="0"
        width="100%">
        <thead>
            <tr>
                <th class="mdl-data-table__cell--non-numeric">{% trans 'Membership number' %}</th>
                {% if perms.members.view_field_last_name %}
                    <th class="mdl-data-table__cell--non-numeric">{% trans 'Lastname' %}</th>
                {% endif %}
                {% if perms.members.view_field_first_name %}
                    <th class="mdl-data-table__cell--non-numeric">{% trans 'Firstname' %}</th>
                {% endif %}
                {% if perms.members.view_field_street %}
                    <th class="mdl-data-table__cell--non-numeric">{% trans 'Street' %}</th>
                {% endif %}
                {% if perms.members.view_field_zipcode %}
                    <th class="mdl-data-table__cell--non-numeric">{% trans 'Zip-Code' %}</th>
                {% endif %}
                {% if perms.members.view_field_city %}
                    <th class="mdl-data-table__cell--non-numeric">{% trans 'City' %}</th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
            {% for member in members %}
                <tr>
                    <td class="mdl-data-table__cell--non-numeric">
                        <a href="{% url 'members:member_detail' pk=member.pk %}" target="_blank">
                            {{ member.membership_number}}
                        </a>
                    </td>
                    {% if perms.members.view_field_last_name %}
                        <td class="mdl-data-table__cell--non-numeric">
                            {{ member.last_name}}
                        </td>
                    {% endif %}
                    {% if perms.members.view_field_first_name %}
                        <td class="mdl-data-table__cell--non-numeric">
                            {{ member.first_name }}
                        </td>
                    {% endif %}
                    {% if perms.members.view_field_street %}
                        <td class="mdl-data-table__cell--non-numeric">
                            {{ member.street }}
                        </td>
                    {% endif %}
                    {% if perms.members.view_field_zipcode %}
                        <td class="mdl-data-table__cell--non-numeric">
                            {{ member.zipcode }}
                        </td>
                    {% endif %}
                    {% if perms.members.view_field_city %}
                        <td class="mdl-data-table__cell--non-numeric">
                            {{ member.city }}
                        </td>
                    {% endif %}
                </tr>
            {% endfor %}
        </tbody>
    </table>
    {% if perms.members.add_member %}
    <a href ="{% url 'members:member_create' %}" class="mdc-fab mdc-fab--absolute-bottom-right" aria-label="" title="{% trans 'Add' %}" target="_blank">
        <i class="mdc-fab__icon fa fa-plus"></i>
    </a>
    {% endif %}
{% endblock %}

{% block foot %}<!-- Datatables -->
    <script src="{% static 'app/vendors/datatables.net/datatables.min.js' %}"></script>
    <script src="{% static 'app/vendors/datatables.net/datatables.material.min.js' %}"></script>
    <script>
        $(document).ready(function () {
            dt = $('#memberslist').on('processing.dt', function (e, settings, processing) {
                $('#memberslist').css('opacity', processing ? '0.3' : '1.0');
            }).DataTable({
                "order": [[1,"asc"]],
                "processing": true,
                "serverSide": false,
                "language": {
                    "sProcessing": "<i class='fa fa-spin fa-spinner fa-3x'></i>",
                    "sEmptyTable": "{% trans 'sEmptyTable' %}",
                    "sInfo": "{% trans 'sInfo' %}",
                    "sInfoEmpty": "{% trans 'sInfoEmpty' %}",
                    "sInfoFiltered": "{% trans 'sInfoFiltered' %}",
                    "sInfoPostFix": "{% trans 'sInfoPostfix' %}",
                    "sInfoThousands": "{% trans 'sInfoThousands' %}",
                    "sLoadingRecords": "{% trans 'sLoadingRecords' %}",
                    "sZeroRecords": "{% trans 'sZeroRecords' %}",
                    "oPaginate": {
                        "sFirst": "{% trans 'sFirst' %}",
                        "sLast": "{% trans 'sLast' %}",
                        "sNext": "{% trans 'sNext' %}",
                        "sPrevious": "{% trans 'sPrevious' %}"
                    },
                    "oAria": {
                        "sSortAscending": "{% trans 'sSortAscending' %}",
                        "sSortDescending": "{% trans 'sSortDescending' %}"
                    }
                },
            });
            // Search
            $("#memberslist_filter").html('<div class="mdc-text-field"><input type="text" id="datatable-search" class="mdc-text-field__input"><label class="mdc-floating-label" for="datatable-search">{% trans 'sSearch' %}</label><div class="mdc-line-ripple"></div></div>');
            $("#datatable-search").on('keyup', function(e) {
                dt.search(this.value).draw();
            })

            // Itemsselect
            $("#memberslist_length").html('<div class="mdc-select"><i class="mdc-select__dropdown-icon"></i>' + $('#memberslist_length select')[0].outerHTML + '<label class="mdc-floating-label">{% trans 'sLengthMenu' %}</label><div class="mdc-line-ripple"></div></div>');
            $(".mdc-select select").addClass("mdc-select__native-control");
            $('#memberslist_length select').on('change', function (e) {
                dt.page.len(this.value).draw();
            });
        });
    </script>
{% endblock %}