pyVerein/app/urls.py
# Import django-urls.
from django.urls import path
# Import views.
from . import views

# Set app name
app_name = 'app'
# Set url-patterns
urlpatterns = [
    path('', views.index, name='index'),
]

pyVerein/reporting/urls.py
# Import django-urls.
from django.urls import path
# Import views.
from . import views

# Set app name
app_name = 'reporting'
# Set url-patterns
urlpatterns = [
    path('', views.ReportIndexView.as_view(), name='list'),
    path('new/', views.ReportCreateView.as_view(), name='create'),
    path('<int:pk>/', views.ReportDetailView.as_view(), name='detail'),
    path('edit/<int:pk>/', views.ReportEditView.as_view(), name='edit'),
    path('run/<int:pk>/', views.run_report, name='run'),
    path('download_report/<int:pk>/', views.download_report, name='download_report'),
    path('upload_resource/<int:pk>/', views.upload_resource, name='upload_resource'),
    path('delete_resource/<int:pk>/', views.delete_resource, name='delete_resource'),
    path('download_resource/<int:pk>/', views.download_resource, name='download_resource'),
    path('download_data/', views.download_data, name='download_data'),
] 

pyVerein/reporting/models.py
from django.db import models
from author.decorators import with_author
from utils.models import ModelBase, AccessRestrictedModel
from django.utils.translation import ugettext_lazy as _
from django.forms import ValidationError
import uuid
from separatedvaluesfield.models import SeparatedValuesField
from author.decorators import with_author

def get_report_path(instance, filename):
    """
    Return reportpath with report id folder
    """
    return "protected/reports/{}/definition/{}".format(instance.uuid, filename)

@with_author
class Report(ModelBase, AccessRestrictedModel):
    """
    Model for storing reports
    """

    class Meta:
        permissions = (
            ('run_report', 'Can run report'),
            ('download_data', 'Can download data'),
            ('download_member_data', 'Can download member data'),
            ('download_division_data', 'Can download division data'),
            ('download_subscription_data', 'Can download subscription data'),
            ('download_account_data', 'Can download account data'),
            ('download_costcenter_data', 'Can download costcenter data'),
            ('download_costobject_data', 'Can download costobject data'),
            ('download_transaction_data', 'Can download transaction data'),
            ('download_closuretransaction_data', 'Can download closuretransaction data'),
            ('download_closurebalance_data', 'Can download closurebalance data'),
        )

    MEMBER = 'MEM'
    DIVISION = 'DIV'
    SUBSCRIPTION = 'SUB'
    ACCOUNT = 'ACC'
    COSTCENTER = 'COC'
    COSTOBJECT = 'COO'
    TRANSACTION = 'TRA'
    CLOSURETRANSACTION = 'CTR'
    CLOSUREBALANCE = 'CBA'

    MODELS = (
        (MEMBER, _('Member')),
        (DIVISION, _('Division')),
        (SUBSCRIPTION, _('Subscription')),
        (ACCOUNT, _('Account')),
        (COSTCENTER, _('Costcenter')),
        (COSTOBJECT, _('Costobject')),
        (TRANSACTION, _('Transaction')),
        (CLOSURETRANSACTION, _('Closuretransaction')),
        (CLOSUREBALANCE, _('Closurebalance'))
    )

    name = models.CharField(null=False, blank=False, max_length=255)
    
    description = models.TextField(null=True, blank=True)

    report = models.FileField(null=True, blank=True, upload_to=get_report_path)

    model = SeparatedValuesField(null=False, blank=False, max_length=255, choices=MODELS, default=[MEMBER])

    jsonql_query = models.TextField(null=False, blank=False)

    uuid = models.UUIDField(default=uuid.uuid4, editable=False)

    resources = models.CharField(blank=True, null=True, max_length=255)
        
    def clean(self, *args, **kwargs):
        super(Report, self).clean(*args, **kwargs)
        if not self.report:
            raise ValidationError(_('Report must not be empty'))

def get_resource_path(instance, filename):
    """
    Return resourcepath with report id folder
    """
    return "protected/reports/{}/resource/{}".format(instance.report.uuid, filename)

@with_author
class Resource(ModelBase):
    """
    Model for report-resource
    """
    report = models.ForeignKey(Report, on_delete=models.CASCADE)

    resource = models.FileField(null=False, blank=False, upload_to=get_resource_path)

pyVerein/reporting/forms.py
from django import forms
from .models import Report, Resource
from django.forms.widgets import FileInput, CheckboxSelectMultiple
from django.utils.translation import ugettext_lazy as _
class ReportForm(forms.ModelForm):
    class Meta:
        model = Report
        fields = ('name', 'description', 'report', 'model', 'jsonql_query', 'user', 'groups')
        widgets = {
            'report': FileInput(),
            'model': CheckboxSelectMultiple(attrs={'class': 'mdc-checkbox__native-control'}),
            'user': CheckboxSelectMultiple(attrs={'class': 'mdc-checkbox__native-control'}),
            'groups': CheckboxSelectMultiple(attrs={'class': 'mdc-checkbox__native-control'})
        }

class ResourceForm(forms.ModelForm):
    class Meta:
        model = Resource
        fields = ('resource',)

pyVerein/reporting/views.py
# Import reverse.
from django.urls import reverse, reverse_lazy
from django.views.generic import TemplateView, UpdateView, CreateView
from django.contrib.auth.decorators import login_required, permission_required
from django.http import HttpResponseBadRequest, JsonResponse, HttpResponseRedirect, HttpResponseForbidden, HttpResponse
from django.db import Error
# Import Report.
from .forms import ReportForm, ResourceForm
from .models import Report, Resource
from members.models import Member, Division, Subscription
from members.serializer import MemberJSONSerializer, DivisionJSONSerializer, SubscriptionJSONSerializer
from finance.models import Transaction, Account, CostCenter, CostObject, ClosureBalance, ClosureTransaction
from finance.serializer import TransactionJSONSerializer, AccountJSONSerializer, CostCenterJSONSerializer, CostObjectJSONSerializer, ClosureBalanceJSONSerializer, ClosureTransactionJSONSerializer
import os
from django.conf import settings

# Import localization
from django.utils.translation import ugettext_lazy as _

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render
from sendfile import sendfile
import io
import uuid
import json
from pyreportjasper.jasperpy import JasperPy, FORMATS as JASPER_FORMATS
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
import os
from utils.views import DetailView

# Index-View.
class ReportIndexView(LoginRequiredMixin, PermissionRequiredMixin, TemplateView):
    permission_required = 'reporting.view_report'
    template_name = 'reporting/list.html'

    def get_context_data(self, **kwargs):
        context = super(ReportIndexView, self).get_context_data(**kwargs)

        reports = Report.objects.all()
        context['reports'] = [report for report in reports if report.is_access_granted(self.request.user)]

        return context


# Detail-View.
class ReportDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    permission_required = 'reporting.view_report'
    model = Report
    context_object_name = 'report'
    template_name = 'reporting/detail.html'

    def get_context_data(self, **kwargs):
        context = super(ReportDetailView, self).get_context_data(**kwargs)

        context['resources'] = Resource.objects.filter(report=self.object)
        context['models'] = [val for key, val in Report.MODELS if key in self.object.model]

        return context

    def has_permission(self):
        super_perm = super(ReportDetailView, self).has_permission()
        return super_perm and Report.objects.get(pk=self.kwargs['pk']).is_access_granted(self.request.user)

# Edit-View.
class ReportEditView(LoginRequiredMixin, PermissionRequiredMixin, SuccessMessageMixin, UpdateView):
    permission_required = ('reporting.view_report', 'reporting.change_report')
    model = Report
    context_object_name = 'report'
    template_name = 'reporting/edit.html'
    form_class = ReportForm
    success_message = _('Report saved sucessfully')

    def get_success_url(self):
        return reverse_lazy('reporting:detail', args={self.object.pk})
    
    def has_permission(self):
        super_perm = super(ReportEditView, self).has_permission()
        return super_perm and Report.objects.get(pk=self.kwargs['pk']).is_access_granted(self.request.user)

# Edit-View.
class ReportCreateView(LoginRequiredMixin, PermissionRequiredMixin, SuccessMessageMixin, CreateView):
    permission_required = ('reporting.view_report', 'reporting.add_report')
    model = Report
    context_object_name = 'report'
    template_name = 'reporting/create.html'
    form_class = ReportForm
    success_message = _('Report created successfully')

    def get_success_url(self):
        return reverse_lazy('reporting:detail', args={self.object.pk})

@login_required
@permission_required(['reporting.view_report', 'reporting.change_report'], raise_exception=True)
def upload_resource(request, pk):
    """
    Upload for report resources
    """
    if request.method == 'POST':
        report = Report.objects.get(pk=pk)

        # Check if user can access report
        if not report.is_access_granted(request.user):
            return HttpResponseForbidden()

        try:
            resource = Resource(report=report, resource=request.FILES['resource'])
            resource.save()

            # Update resource list for history
            report.resources = ",".join([os.path.basename(r.resource.file.name) for r in Resource.objects.filter(report=report)])
            report.save()
        except Error as err:
            return JsonResponse({'error': err})
        
        return JsonResponse({'state': 'success'})
    else:
        return HttpResponseBadRequest()    

@login_required
@permission_required(['reporting.view_report', 'reporting.change_report'], raise_exception=True)
def delete_resource(request, pk):
    """
    Delete report resources
    """
    if request.method == 'POST':
        resource = Resource.objects.get(pk=pk)
        report = resource.report

        # Check if user can access report
        if not report.is_access_granted(request.user):
            return HttpResponseForbidden()

        resource.delete()
        if os.path.isfile(os.path.join(settings.MEDIA_ROOT, resource.resource.path)):
            os.remove(os.path.join(settings.MEDIA_ROOT, resource.resource.path))
        
        # Update resource list for history
        report.resources = ",".join([os.path.basename(r.resource.file.name) for r in Resource.objects.filter(report=report)])
        report.save()
        return HttpResponseRedirect(reverse_lazy('reporting:detail', kwargs={'pk': report.pk}))
    else:
        return HttpResponseBadRequest() 

@login_required
@permission_required(['reporting.view_report'], raise_exception=True)
def download_resource(request, pk):
    """
    Download resource with X-SENDFILE header
    """
    resource = Resource.objects.get(pk=pk)
    # Check if user can access member
    if not resource.report.is_access_granted(request.user):
        return HttpResponseForbidden()

    file = resource.resource
    return sendfile(request, file.path, attachment=True, attachment_filename=os.path.basename(file.name))

@login_required
@permission_required(['reporting.view_report', 'reporting.change_report'], raise_exception=True)
def download_report(request, pk):
    """
    Download reportdefinition with X-SENDFILE header
    """
    report = Report.objects.get(pk=pk)
    # Check if user can access report
    if not report.is_access_granted(request.user):
        return HttpResponseForbidden()

    file = report.report
    return sendfile(request, file.path, attachment=True, attachment_filename=os.path.basename(file.name))

@login_required
@permission_required(['reporting.view_report', 'reporting.run_report'], raise_exception=True)
def run_report(request, pk):
    """
    Run report and return generated file
    """
    report = Report.objects.get(pk=pk)
    # Check if user can access report
    if not report.is_access_granted(request.user):
        return HttpResponseForbidden()
    
    # Get report definition
    report_definition = report.report.path
    jasperpy = JasperPy()
    parameters = jasperpy.list_parameters(report_definition).keys()
    if request.method == 'GET':
        context = {
            'report': report,
            'parameters': parameters,
            'formats': JASPER_FORMATS,
        }
        return render(request, 'reporting/run.html', context)
        
    
    if request.method == 'POST':
        # Get POST-Parameter
        parameter_map = {}
        for param in parameters:
            val = request.POST.get(param, None)
            if not val:
                return HttpResponseBadRequest()
            parameter_map.update({
                param: val
            })
        file_format = request.POST.get('format', None)
        if not file_format:
            return HttpResponseBadRequest()
        # Create data-JSON file
        modelmap = {
            'MEM': {
                'model': Member,
                'serializer': MemberJSONSerializer,
            },
            'DIV': {
                'model': Division,
                'serializer': DivisionJSONSerializer,
            },
            'SUB': {
                'model': Subscription,
                'serializer': SubscriptionJSONSerializer,
            },
            'ACC': {
                'model': Account,
                'serializer': AccountJSONSerializer,
            },
            'COC': {
                'model': CostCenter,
                'serializer': CostCenterJSONSerializer,
            },
            'COO': {
                'model': CostObject,
                'serializer': CostObjectJSONSerializer,
            },
            'TRA': {
                'model': Transaction,
                'serializer': TransactionJSONSerializer,
            },
            'CTR': {
                'model': ClosureTransaction,
                'serializer': ClosureTransactionJSONSerializer,
            },
            'CBA': {
                'model': ClosureBalance,
                'serializer': ClosureBalanceJSONSerializer,
            }
        }
        json_data = {}
        for model in set(report.model):
            json_data.update(modelmap[model]['serializer']().serialize(modelmap[model]['model'].objects.all()))
        # Write JSON-data
        data_filepath = os.path.join(settings.MEDIA_ROOT, "protected/reports/{}/data/{}".format(report.uuid, str(uuid.uuid4()) + '.json'))
        os.makedirs(os.path.dirname(data_filepath), exist_ok=True)
        with io.open(data_filepath, 'w', encoding='utf8') as f:
            f.write(json.dumps(json_data))
        
        # Output file
        output_filepath = os.path.join(settings.MEDIA_ROOT, "protected/reports/{}/output/{}-{}".format(report.uuid, report.name, str(uuid.uuid4())))

pyVerein/reporting/templates/reporting/create.html
{% extends 'app/base.html' %}
{% load i18n %}
{% load widget_tweaks %}
{% load static %}
{% get_current_language as LANGUAGE_CODE %}

{% block page_title %}
    {% trans 'Create report' %}
{% endblock %}

{% block title %}
    {% trans 'Create report' %}
{% endblock %}

{% block content %}
    <div class="main-narrow form">
        <div class="detail-content  mdc-elevation--z4">
            <form action="{% url 'reporting:create' %}" method="POST" id="form" enctype="multipart/form-data">
                {% include 'reporting/form_fields.html' %}
                <div class="form-group form-submit">
                    <input type="submit" class="mdc-button mdc-button--raised" value="{% trans 'Save' %}" title="{% trans 'Save' %}" />
                    <a href="{% url 'reporting:list' %}" class="mdc-button" title="{% trans 'Cancel' %}">{% trans 'Cancel' %}</a>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

{% block foot %}
    <script>
        $('#reportdefinition').click(function (e){
            $('#id_report').click();
            e.preventDefault();
        });
        $('#id_report').change(function(e){
            file = this.files[0];
            
            $('#info_reportdefinition').html(file.name);
        });
    </script>
    <!-- Keys -->
    <script src="{% static 'app/js/keys.js' %}"></script>
    <script>
        $('#form').saveOnTimes();
        $('#form').nextOnEnter();
    </script>
{% endblock %}

pyVerein/reporting/templates/reporting/detail.html
{% extends 'app/base.html' %}
{% load i18n %}
{% load static %}
{% load filename %}

{% block page_title %}
    {% trans 'Report-Detail' %}
{% endblock %}

{% block title %}
    {{ report.name }}
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'app/vendors/dropzone.js/dropzone.min.css' %}">
    <!-- DataTables -->
    <link rel="stylesheet" href="{% static 'app/vendors/datatables.net/material.min.css' %}">
    <link rel="stylesheet" href="{% static 'app/vendors/datatables.net/datatables.material.min.css' %}">
{% endblock %}

{% block content %}
    <div class="main-narrow form">
        <div class="detail-content mdc-elevation--z4">
            <div class="heading mdc-typography--overline">
                {% trans 'Report' %}
            </div>
            <div class="row">
                <div class="field-title">{% trans 'Description' %}</div>
                <div class="field-value">{{ report.description }}</div>
            </div>
            <div class="row">
                <div class="field-title">{% trans 'Reportdefinition' %}</div>
                <div class="field-value"><a href="{% url 'reporting:download_report' pk=report.pk %}" title="{% trans 'Download reportdefinition' %}" target="blank">{% trans 'Download' %}</a></div>
            </div>
            <div class="row">
                <div class="field-title">{% trans 'JSONQL-Query' %}</div>
                <div class="field-value">{{ report.jsonql_query }}</div>
            </div>
            <div class="row">
                <div class="field-title">{% trans 'Models' %}</div>
                <div class="field-value">{% for model in models %}{{ model }} {% endfor %}</div>
            </div>
            <div class="heading mdc-typography--overline">
                {% trans 'Access restrictions' %}
            </div>
            <div class="row">
                <div class="field-title">{% trans 'User' %}</div>
                <div class="field-value">
                    {% if report.user.all %}
                        {% for user in report.user.all %}
                            {{ user }}{% if not forloop.last %},{% endif %}
                        {% endfor %}
                    {% else %}
                        {% trans 'Access not restricted' %}
                    {% endif %}
                </div>
            </div>
            <div class="row">
                <div class="field-title">{% trans 'Groups' %}</div>
                <div class="field-value">
                    {% if report.groups.all %}
                        {% for group in report.groups.all %}
                            {{ group }}{% if not forloop.last %},{% endif %}
                        {% endfor %}
                    {% else %}
                        {% trans 'Access not restricted' %}
                    {% endif %}
                </div>
                </div>
            <div class="heading mdc-typography--overline">
                {% trans 'Resources' %}
            </div>
            <div class="row">
                <table id="resources" class="mdl-data-table mdl-js-data-table" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th class="mdl-data-table__cell--non-numeric">{% trans 'Filename' %}</th>
                            <th class="mdl-data-table__cell--non-numeric">{% trans 'Action' %}</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for resource in resources %}
                            <tr>
                                <td class="mdl-data-table__cell--non-numeric">
                                    {{ resource.resource|filename }}
                                </td>
                                <td class="mdl-data-table__cell--non-numeric">
                                    <a href="{% url 'reporting:download_resource' pk=resource.pk %}" title="{% trans 'Download' %}">{% trans 'Download' %}</a>
                                    <form action="{% url 'reporting:delete_resource' pk=resource.pk %}" method="POST">{% csrf_token %}<a href="#" class="submit" title="{% trans 'Delete' %}">{% trans 'Delete' %}</a></form>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="row">
                <form action="{% url 'reporting:upload_resource' pk=report.pk %}" method="POST" enctype="multipart/form-data" class="dropzone" id="resource_upload">
                    <div class="dz-message">
                        <div class="drag-icon-cph">
                            <i class="mdc-fab__icon fa fa-upload"></i>
                        </div>
                        <h3>{% trans 'Drop files here or click to upload.' %}</h3>
                    </div>
                </form>
            </div>
        </div>
    </div>
    {% if perms.reporting.change_report %}
    <a href ="{% url 'reporting:edit' pk=report.pk %}" class="mdc-fab mdc-fab--absolute-bottom-right" aria-label="" title="{% trans 'Edit' %}">
        <i class="mdc-fab__icon fa fa-pencil-alt"></i>
    </a>
    {% endif %}
{% endblock %}

{% block foot %}
    <!-- Cookie.js -->
    <script src="{% static 'app/js/cookie.js' %}"></script>
    <script src="{% static 'app/vendors/dropzone.js/dropzone.min.js' %}"></script>
    <script>
        Dropzone.options.resourceUpload = {
            paramName: "resource",
            uploadMultiple: false,
            headers: {
                "X-CSRFToken": getCookie('csrftoken')
            }
        }
        $('a.submit').on('click', function(){
            $(this).parent().submit();
        })
    </script>
{% endblock %}

pyVerein/reporting/templates/reporting/edit.html
{% extends 'app/base.html' %}
{% load i18n %}
{% load widget_tweaks %}
{% load static %}
{% load filename %}
{% get_current_language as LANGUAGE_CODE %}

{% block head %}

{% endblock %}

{% block page_title %}
    {% trans 'Edit report' %}
{% endblock %}

{% block title %}
    {% trans 'Edit report' %}
{% endblock %}

{% block content %}
<div class="main-narrow form">
    <div class="detail-content  mdc-elevation--z4">
        <form action="{% url 'reporting:edit' report.pk %}" method="POST" id="form" enctype="multipart/form-data">
            {% include 'reporting/form_fields.html' %}
            <div class="form-group form-submit">
                <input type="submit" class="mdc-button mdc-button--raised" value="{% trans 'Save' %}" title="{% trans 'Save' %}" />
                <a href="{% url 'reporting:detail' pk=report.pk %}" class="mdc-button" title="{% trans 'Cancel' %}">{% trans 'Cancel' %}</a>
            </div>
        </form>
    </div>
</div>
   
{% endblock %}

{% block foot %}
    <script>
        $('#reportdefinition').click(function (e){
            $('#id_report').click();
            e.preventDefault();
        });
        $('#id_report').change(function(e){
            file = this.files[0];
            
            $('#info_reportdefinition').html(file.name);
        });
        $('#info_reportdefinition').html('{{ report.report|filename }}');
    </script>
    <!-- Keys -->
    <script src="{% static 'app/js/keys.js' %}"></script>
    <script>
        $('#form').saveOnTimes();
        $('#form').nextOnEnter();
    </script>
{% endblock %}

pyVerein/reporting/templates/reporting/list.html
{% extends 'app/base.html' %}
{% load i18n %}
{% load static %}

{% block head %}
    <!-- DataTables -->
    <link rel="stylesheet" href="{% static 'app/vendors/datatables.net/material.min.css' %}">
    <link rel="stylesheet" href="{% static 'app/vendors/datatables.net/datatables.material.min.css' %}">
{% endblock %}

{% block page_title %}
    {% trans 'Report-List' %}
{% endblock %}

{% block title %}
    {% trans 'Report-List' %}
{% endblock %}

{% block content %}
    <table id="reports" class="mdl-data-table mdl-js-data-table" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th class="mdl-data-table__cell--non-numeric">{% trans 'Name' %}</th>
                <th class="mdl-data-table__cell--non-numeric">{% trans 'Description' %}</th>
                <th class="mdl-data-table__cell--non-numeric">{% trans 'Action' %}</th>
            </tr>
        </thead>
        <tbody>
            {% for report in reports %}
                <tr>
                    <td class="mdl-data-table__cell--non-numeric">
                        <a href="{% url 'reporting:detail' pk=report.pk %}" target="_blank">
                            {{ report.name}}
                        </a>
                    </td>
                    <td class="mdl-data-table__cell--non-numeric">
                        {{ report.description }}
                    </td>
                    <td class="mdl-data-table__cell--non-numeric">
                        <a href="{% url 'reporting:run' pk=report.pk %}" title="{% trans 'Run' %}" class="mdc-button mdc-button--outlined run" target="_blank">{% trans 'Run' %}</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    {% if perms.reporting.add_report %}
    <a href="{% url 'reporting:create' %}" class="mdc-fab mdc-fab--absolute-bottom-right" aria-label="" title="{% trans 'Create' %}" target="_blank">
        <i class="mdc-fab__icon fa fa-plus"></i>
    </a>
    {% endif %}
    {% if perms.reporting.download_data %}
    <a href="{% url 'reporting:download_data' %}" class="mdc-fab mdc-fab--absolute-bottom-right{% if perms.reporting.add_report %} second{% endif %}" aria-label="" title="{% trans 'Download data' %}" target="_blank">
        <i class="mdc-fab__icon fa fa-download"></i>
    </a>
    {% endif %}
{% endblock %}

{% block foot %}<!-- Datatables -->
    <script src="{% static 'app/vendors/datatables.net/datatables.min.js' %}"></script>
    <script src="{% static 'app/vendors/datatables.net/datatables.material.min.js' %}"></script>

    <script>
        $(document).ready(function () {
            dt = $('#reports').on('processing.dt', function (e, settings, processing) {
                $('#reports').css('opacity', processing ? '0.3' : '1.0');
            }).DataTable({
                "processing": true,
                "serverSide": false,
                "language": {
                    "sProcessing": "<i class='fa fa-spin fa-spinner fa-3x'></i>",
                    "sEmptyTable": "{% trans 'sEmptyTable' %}",
                    "sInfo": "{% trans 'sInfo' %}",
                    "sInfoEmpty": "{% trans 'sInfoEmpty' %}",
                    "sInfoFiltered": "{% trans 'sInfoFiltered' %}",
                    "sInfoPostFix": "{% trans 'sInfoPostfix' %}",
                    "sInfoThousands": "{% trans 'sInfoThousands' %}",
                    "sLoadingRecords": "{% trans 'sLoadingRecords' %}",
                    "sZeroRecords": "{% trans 'sZeroRecords' %}",
                    "oPaginate": {
                        "sFirst": "{% trans 'sFirst' %}",
                        "sLast": "{% trans 'sLast' %}",
                        "sNext": "{% trans 'sNext' %}",
                        "sPrevious": "{% trans 'sPrevious' %}"
                    },
                    "oAria": {
                        "sSortAscending": "{% trans 'sSortAscending' %}",
                        "sSortDescending": "{% trans 'sSortDescending' %}"
                    }
                },
            });
            // Search
            $("#reports_filter").html('<div class="mdc-text-field"><input type="text" id="datatable-search" class="mdc-text-field__input"><label class="mdc-floating-label" for="datatable-search">{% trans 'sSearch' %}</label><div class="mdc-line-ripple"></div></div>');
            $("#datatable-search").on('keyup', function(e) {
                dt.search(this.value).draw();
            })

            // Itemsselect
            $("#reports_length").html('<div class="mdc-select"><i class="mdc-select__dropdown-icon"></i>' + $('#reports_length select')[0].outerHTML + '<label class="mdc-floating-label">{% trans 'sLengthMenu' %}</label><div class="mdc-line-ripple"></div></div>');
            $(".mdc-select select").addClass("mdc-select__native-control");
            $('#reports_length select').on('change', function (e) {
                dt.page.len(this.value).draw();
            });
            $('a.run').click(function(e){
                e.stopPropagation();
            })
        });


    </script>
{% endblock %}

pyVerein/reporting/templates/reporting/run.html
{% extends 'app/base.html' %}
{% load i18n %}
{% load static %}
{% load filename %}

{% block page_title %}
    {% trans 'Run report' %}
{% endblock %}

{% block title %}
    {% blocktrans with report_name=report.name %}Run report: {{ report_name }}{% endblocktrans %}
{% endblock %}

{% block head %}
{% endblock %}

{% block content %}
    <div class="main-narrow form">
        <div class="detail-content mdc-elevation--z4">
            <form action="{% url 'reporting:run' report.pk %}" method="POST" id="form">
                {% csrf_token %}
                <div class="heading mdc-typography--overline">
                    {% trans 'Parameters' %}
                </div>
                {% for parameter in parameters %}
                    <div class="row full-width">
                        <div class="mdc-text-field mdc-input">
                            <input type="text" class="mdc-text-field__input" name="{{ parameter }}" id="{{ parameter }}" required>
                            <label class="mdc-floating-label" for="{{ parameter }}">
                                {{ parameter }}
                            </label>
                            <div class="mdc-line-ripple"></div>
                        </div>
                    </div>
                {% endfor %}
                <div class="heading mdc-typography--overline">
                    {% trans 'Options' %}
                </div>
                <div class="row">
                    <div class="mdc-select mdc-input">
                        <i class="mdc-select__dropdown-icon"></i>
                        <select id="format" name="format" class="mdc-select__native-control">
                            {% for format in formats %}
                                <option value="{{ format }}">{{ format|upper }}</option>
                            {% endfor %}
                        </select>
                        <label class="mdc-floating-label">{% trans 'Fileformat' %}</label>
                        <div class="mdc-line-ripple"></div>
                    </div>
                </div>
                <div class="form-group form-submit">
                    <input type="submit" class="mdc-button mdc-button--raised" value="{% trans 'Run' %}" title="{% trans 'Run' %}" />
                    <a href="javascript:window.close()" class="mdc-button" title="{% trans 'Cancel' %}">{% trans 'Cancel' %}</a>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

{% block foot %}
{% endblock %}